### ISSUE TITLE
Support for HTTP basic auth in Kontena Loadbalancer

### ISSUE THREAD

**Issue by matti** [kontena/kontena#1053]
Single user/pass would be a good start

**Comment by kke** [comment]
For stats, backends or frontends?

**Comment by matti** [comment]
"web apps deployed in kontena"

**Comment by kke** [comment]
Ok. Adding reminder here how I think it should look like in the haproxy config:

```
userlist auth_users_www_app
  user user1 password <bcrypt_password>
  user user2 insecure-password pass1234

frontend www_app
    .....
    acl auth_ok_www_app http_auth(auth_users_www_app)
    http-request auth realm www_app unless auth_ok_www_app
```

**Comment by jnummelin** [comment]
I'm thinking something like this. In the service which you have behind LB:
```
environment:
    - KONTENA_LB_BASIC_AUTH_SECRET=BASIC_AUTH_FOR_XYZ
secrets:
      - secret: BASIC_AUTH_FOR_XYZ
        name: BASIC_AUTH_FOR_XYZ
        type: env
```

The to write the secret use something like:
```
$ kontena vault write BASIC_AUTH_FOR_XYZ << EOF
→ user user1 password <bcrypt_password>
→ user user2 insecure-password pass1234
→ EOF
```

Would this kind of setup be simple enough?

Of course the docs should be have the usual warnings about basic auth limitations.

**Comment by matti** [comment]
could it be simplified (no env "pointers")

```
secrets:
  - secret: BASIC_AUTH_FOR_XYZ
    name: KONTENA_LB_BASIC_AUTH_SECRET
    type: env
```

```
$ kontena vault write BASIC_AUTH_FOR_XYZ << EOF
→ user user1 password <bcrypt_password>
→ user user2 insecure-password pass1234
→ EOF
```

So users would be split with \n
