### ISSUE TITLE
Missing service secrets are silently ignored

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#1130]
If a service refers to kontena vault secrets, but those secrets are not configured in the vault, the service create/deploy succeeds, but the service itself is likely to fail. Service secrets should be either required or optional, and a missing required secret should cause the service deploy to fail early with a useful error message. Useful error messages are a good thing.

```
mysql:
    image: mariadb:5.5
    stateful: true
    links: []
    secrets:
        - secret: wordpress-mysql-root
          name: MYSQL_ROOT_PASSWORD
          type: env
        - secret: wordpress-mysql
          name: MYSQL_PASSWORD
          type: env
    environment:
        MYSQL_DATABASE: wordpress
        MYSQL_USER: wordpress
```

`kontena vault ls`

```
NAME                                                   CREATED AT                UPDATED AT   
```

`kontena service logs wordpress-mysql`:

```
2016-10-13T12:30:24.000Z [1]: error: database is uninitialized and password option is not specified 
2016-10-13T12:30:24.000Z [1]:   You need to specify one of MYSQL_ROOT_PASSWORD, MYSQL_ALLOW_EMPTY_PASSWORD and MYSQL_RANDOM_ROOT_PASSWORD
```
