### ISSUE TITLE
kontena vault generate secrets

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#1132]
Generating random vault secrets would be a useful feature for new deployments.

Something like `kontena vault generate wordpress-mysql-root` that generates some nice 32-char random secret, vs `kontena vault write wordpress-mysql-root $(pwgen -s 32 1)`

Ideally, `kontena vault generate` would refuse to override an existing secret without some `--force` flag, to avoid accidential reconfigurations.

**Comment by SpComb** [comment]
This is there in the Kontena 1.0 stacks YAML:

```
variables:
  wordpress-mysql-root:
    type: string
    from:
      vault: wordpress-mysql-root
      random_string: 32
    to:
      vault: wordpress-mysql-root
```

This will generate a new `wordpress-mysql-root` kontena vault secret when installing the stack.
