### ISSUE TITLE
Exposing ports through kontena cli not properly updating docker

### ISSUE THREAD

**Issue by timolehto** [kontena/kontena#1208]
```
#on my machine
kontena service ls
NAME                                                         INSTANCES  STATEFUL STATE      EXPOSED PORTS                                     
⊝ qagyver-builder                                            1 / 1      yes      running                                                      
⊝ qagyver-registry                                           1 / 1      yes      running                                                      
⊝ loadbalancer                                               1 / 1      no       running    0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:12222->12222/tcp, 0.0.0.0:12223->12223/tcp
#looking good.. 12223 seems to be open

#And then on the node:
core@timogrid-node-0 ~ $ docker port loadbalancer-1
443/tcp -> 0.0.0.0:443
80/tcp -> 0.0.0.0:80
```

As I try to ssh to qagyver-builder on port 12223 it this works on the node:

```
ssh -T git@loadbalancer -p 12223
```

But if I try to access through localhost or through the nodes public dns it does not accept connections to 12223. Are docker/kontena port exports somehow mixed out of sync and thus this doesn't work?

Ran the configure script again and now it updated and everything works. It looks like there’s a bug in kontena that if you do:

```
kontena app deploy # has some default port configs
kontena service update —ports # replace yml port defs with something more dynamic…
#-> kontena service ls shows new port defs, but docker is using originals from yml
```

**Comment by timolehto** [comment]
Omg, I forgot about this bug and fell in to this trap again...

**Comment by jnummelin** [comment]
Does it still fail to update the ports properly if you do `kontena service deploy xxx` after the update?

**Comment by timolehto** [comment]
You mean like?
```
kontena app deploy -f kontena.yml &&
kontena service update \
  --ports 80:80 \
  --ports 443:443 \
  --ports 12222:12222 servicename &&
kontena service deploy servicename
```

I suppose that could work... I'll give it a try at some point

Right now I'm just doing app deploy, then sleep a bit, tehn update ports, then sleep a bit, then test it's working..

**Comment by timolehto** [comment]
If I do that then I get:
```
 [fail] Deploying service servicename
 [error] Not found
```

I suppose I could just loop there until it succeeds, but it's getting awfully laborious...

**Comment by jnummelin** [comment]
I think the `Not found` issue in deployment was a bug which was fixed in 1.0.1. 

I'm failing to reproduce this with following steps:
```
$ k app deploy -f web-app.yml -p web
 [done] Creating web      
 [done] Deploying web 

$ k service ls
NAME                                                         INSTANCES  STATEFUL STATE      EXPOSED PORTS                                     
⊝ web-web                                                    1 / 1      no       running    0.0.0.0:9999->80/tcp

$ k service update -p 9999:80 -p 9090:80  web-web
 [done] Updating web-web service 

$ k service ls
NAME                                                         INSTANCES  STATEFUL STATE      EXPOSED PORTS                                     
⊝ web-web                                                    1 / 1      no       running    0.0.0.0:9999->80/tcp, 0.0.0.0:9090->80/tcp

$ docker port null-web-web-1
80/tcp -> 0.0.0.0:9090
80/tcp -> 0.0.0.0:9999
```

@timolehto Did I miss some steps or other details?

**Comment by timolehto** [comment]
It seems like this probly works now as this test succeeds already with the first curl when just given enough sleep time. Previously it was so that even though the update would instantly update the ports you see with `kontena service ls` docker ports wouldn't get updated and ultimately the container wouldn't have those ports open until you'd do a redeploy. Now it looks like it's actually working. Have to still confirm this by redeploying localgyver from scratch with updated lb config script:

```
kontena app deploy -f web-app.yml && kontena service update -p 9999:80 web-web && sleep 12 && kontena service ls | grep web-web && echo $(docker port null-web-web-1) && curl localhost:9999; kontena service deploy web-web && sleep 1 && curl localhost:9999
 [done] Creating web      
 [done] Deploying web      
 [done] Updating web-web service      
⊝ web-web                                                    1 / 1      no       running    0.0.0.0:9999->80/tcp                              
80/tcp -> 0.0.0.0:9999
<html>
<head>
	<title>Hello world!</title>
	<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'>
	<style>
	body {
		background-color: white;
		text-align: center;
		padding: 50px;
		font-family: "Open Sans","Helvetica Neue",Helvetica,Arial,sans-serif;
	}

	#logo {
		margin-bottom: 40px;
	}
	</style>
</head>
<body>
	<img id="logo" src="logo.png" />
	<h1>Hello world!</h1>
	<h3>My hostname is web-web-1</h3>	</body>
</html>
 [done] Deploying service web-web      
<html>
<head>
	<title>Hello world!</title>
	<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'>
	<style>
	body {
		background-color: white;
		text-align: center;
		padding: 50px;
		font-family: "Open Sans","Helvetica Neue",Helvetica,Arial,sans-serif;
	}

	#logo {
		margin-bottom: 40px;
	}
	</style>
</head>
<body>
	<img id="logo" src="logo.png" />
	<h1>Hello world!</h1>
	<h3>My hostname is web-web-1</h3>	</body>
</html>
```

**Comment by timolehto** [comment]
Actually today I ran our entire setup script again and it happened again (I updated docker for mac version in between, but likely not relevant here). So there maybe is something that makes this sometimes work and sometimes not:

```
#lb deployed and updated ages ago, kontena shows ports updated
Timos-MacBook-Pro:kontena-xgyver timo$ kontena service show loadbalancer
localgyver/null/loadbalancer:
  stack: localgyver/null
  status: running
  image: kontena/lb:latest
  revision: 4
  stateful: no
  scaling: 1
  strategy: daemon
  deploy_opts:
    min_health: 0.8
    wait_for_port: 80
  dns: loadbalancer.localgyver.kontena.local
  secrets: 
    - secret: LOCALGYVER_COM_CERT_PEM
      name: SSL_CERTS
      type: env
  env: 
    - CONFIGURED_ENVS=localgyver
  net: bridge
  ports:
    - 80:80/tcp
    - 443:443/tcp
    - 12222:12222/tcp
  instances:
    null-loadbalancer-1:
      rev: 2016-12-21 07:56:59 UTC
      service_rev: 2
      node: moby
      dns: loadbalancer-1.localgyver.kontena.local
      ip: 10.81.128.69
      public ip: 185.11.211.158
      status: running
      exit code: 0

docker port null-loadbalancer-1
443/tcp -> 0.0.0.0:443
80/tcp -> 0.0.0.0:80
```
