### ISSUE TITLE
kontena stack registry show available_version sorting

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#1422]
This `sort` thing only kinda works:

```ruby
      stacks_client.versions(stack_name).map { |s| s['version']}.sort.reverse_each do |version| 
```

> @kke It could use `sort {|a,b| Gem::Version.new(a) <=> Gem::Version.new(b)}`
> @kke or replace the .map with `.map {|v| Gem::Version.new(v['version']}.sort`

#### `kontena stack registry show terom/redis`
```yaml
terom/redis:
  latest_version: 0.10.0
  expose: -
  description: -
  available_versions:
    - 0.2.0
    - 0.10.0
    - 0.1.1
```
