### ISSUE TITLE
kontena stack registry show --versions, :version

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#1423]
The `kontena stack registry show --versions` flag to only output the version numbers got clobbered in #1403 

It also ignores any `kontena stack registry show foo/bar:version` -> `stack_version`. The "latest_version" is probably a bit of a misnomer in this case.

#### `kontena stack registry show terom/redis:0.10.1`
```yaml
terom/redis:
  latest_version: 0.11.0
  expose: -
  description: This is version 0.11
  available_versions:
      ...
```
