### ISSUE TITLE
document stack file in references

### ISSUE THREAD

**Issue by matti** [kontena/kontena#1471]
Currently stacks documentation only mentions `expose:` key and does not mention anything about `variables:`

**Comment by kke** [comment]
While waiting, there's some documentation in https://github.com/kontena/opto readme

**Comment by matti** [comment]
adding to the `:latest` documentation:

```
variables:
  beer:
    from: 
      env: BEER_TYPE
      prompt: You didn't specify BEER_TYPE as an env-variable, so please specify it now
```
