### ISSUE TITLE
stacks yml variables result always in value "filler"

### ISSUE THREAD

**Issue by matti** [kontena/kontena#1473]
Given following:

```
variables:
  node_password:
    type: string
    from:
      vault: ${PROJECT}_REDIS_SENTINEL_PASSWORD
      prompt: Redis password
    to:
      vault: ${PROJECT}_REDIS_SENTINEL_PASSWORD
```

and command `kontena stack install -n myname stackfile.yml` results says:

```
> Redis password : asdf
Value for PROJECT is not set. Substituting with an empty string.
Value for PROJECT is not set. Substituting with an empty string.
```

And in kontena vault key is:

```
filler_REDIS_SENTINEL_PASSWORD
```

So it's not "empty" and shouldn't be: I think that the install / deploy should be aborted.
