### ISSUE TITLE
Stacks with LB can cause conflicts in LB configs

### ISSUE THREAD

**Issue by jnummelin** [kontena/kontena#1480]
Consider having two stacks:
```
stack: jussi/web-a
description: Web A
version: 0.0.1
variables:
services:
  lb:
    image: kontena/lb
    
  web:
    image: nginx
    links:
      - lb
    environment:
      - KONTENA_LB_VIRTUAL_PATH=/A


stack: jussi/web-b
description: Web B
version: 0.0.1
variables:
services:
  lb:
    image: kontena/lb
    
  web:
    image: nginx
    links:
      - lb
    environment:
      - KONTENA_LB_VIRTUAL_PATH=/B

```

Both of the loadbalancers will read the same "tree" in ETCD as it picks up the correct tree from env `KONTENA_SERVICE_NAME`. Also agent will write the service and instance configs into the same tree and possibly conflic/overwrite the other stacks configs. :(

The `KONTENA_SERVICE_NAME` env needs to be stacks aware and also the loadbalancer linking has to be made stacks aware.
