### ISSUE TITLE
YAML loading fails when extended file contains "networks" section.

### ISSUE THREAD

**Issue by jrasanen** [kontena/kontena#1484]
Kontena app deploy command fails when docker-compose.yml has "networks" section.

1. docker-compose.yml has `networks` section for services
2. kontena.yml extends it
3. Error thrown (pasted below)

```shell
/Users/jussir/.rvm/gems/ruby-2.3.1/gems/kontena-cli-1.0.0/lib/kontena/cli/apps/yaml/service_extender.rb:19:in `extend': undefined method `[]' for nil:NilClass (NoMethodError)
	from /Users/jussir/.rvm/gems/ruby-2.3.1/gems/kontena-cli-1.0.0/lib/kontena/cli/apps/yaml/reader.rb:149:in `extend_config'
	from /Users/jussir/.rvm/gems/ruby-2.3.1/gems/kontena-cli-1.0.0/lib/kontena/cli/apps/yaml/reader.rb:108:in `process_config'
	from /Users/jussir/.rvm/gems/ruby-2.3.1/gems/kontena-cli-1.0.0/lib/kontena/cli/apps/yaml/reader.rb:93:in `block in parse_services'
	from /Users/jussir/.rvm/gems/ruby-2.3.1/gems/kontena-cli-1.0.0/lib/kontena/cli/apps/yaml/reader.rb:92:in `each'
	from /Users/jussir/.rvm/gems/ruby-2.3.1/gems/kontena-cli-1.0.0/lib/kontena/cli/apps/yaml/reader.rb:92:in `parse_services'
	from /Users/jussir/.rvm/gems/ruby-2.3.1/gems/kontena-cli-1.0.0/lib/kontena/cli/apps/yaml/reader.rb:33:in `block in execute'
	from /Users/jussir/.rvm/gems/ruby-2.3.1/gems/kontena-cli-1.0.0/lib/kontena/cli/apps/yaml/reader.rb:28:in `chdir'
	from /Users/jussir/.rvm/gems/ruby-2.3.1/gems/kontena-cli-1.0.0/lib/kontena/cli/apps/yaml/reader.rb:28:in `execute'
	from /Users/jussir/.rvm/gems/ruby-2.3.1/gems/kontena-cli-1.0.0/lib/kontena/cli/apps/common.rb:23:in `services_from_yaml'
	from /Users/jussir/.rvm/gems/ruby-2.3.1/gems/kontena-cli-1.0.0/lib/kontena/cli/apps/deploy_command.rb:29:in `execute'
	from /Users/jussir/.rvm/gems/ruby-2.3.1/gems/kontena-cli-1.0.0/lib/kontena/command.rb:187:in `run'
	from /Users/jussir/.rvm/gems/ruby-2.3.1/gems/clamp-1.1.1/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /Users/jussir/.rvm/gems/ruby-2.3.1/gems/kontena-cli-1.0.0/lib/kontena/command.rb:187:in `run'
	from /Users/jussir/.rvm/gems/ruby-2.3.1/gems/clamp-1.1.1/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /Users/jussir/.rvm/gems/ruby-2.3.1/gems/kontena-cli-1.0.0/lib/kontena/command.rb:187:in `run'
	from /Users/jussir/.rvm/gems/ruby-2.3.1/gems/clamp-1.1.1/lib/clamp/command.rb:132:in `run'
	from /Users/jussir/.rvm/gems/ruby-2.3.1/gems/kontena-cli-1.0.0/bin/kontena:16:in `<top (required)>'
	from /Users/jussir/.rvm/gems/ruby-2.3.1/bin/kontena:23:in `load'
	from /Users/jussir/.rvm/gems/ruby-2.3.1/bin/kontena:23:in `<main>'
	from /Users/jussir/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/jussir/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

### docker-compose.yml
```yml
version: '2'
services:

  elasticsearch:
    build: elasticsearch/
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    networks:
      - loki

  fluentd:
    build: fluentd/
    ports:
      - "9292:9292"
      - "9880:9880"
      - "24224:24224"
      - "24284:24284"
      - "5170:5170"
    volumes:
      - ./fluentd/:/fluentd/etc/
    depends_on:
      - elasticsearch
    networks:
      - loki

  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/opt/kibana/config/
    ports:
      - "5601:5601"
    networks:
      - loki
    depends_on:
      - elasticsearch

networks:
  loki:
    driver: bridge
```

### kontena.yml
```yml
version: "2"
services:

  elasticsearch:
    image: image-registry.leonidasoy.fi/loki-elasticsearch:v1
    ports: []
    volumes: []
    stateful: true
    extends:
      file: docker-compose.yml
      service: elasticsearch

  fluentd:
    image: image-registry.leonidasoy.fi/loki-fluentd:v1
    ports: []
    volumes: []
    extends:
      file: docker-compose.yml
      service: fluentd
    external_links:
      - external-loadbalancer-lb1
    environment:
      - KONTENA_LB_MODE=tcp

  kibana:
    image: image-registry.leonidasoy.fi/loki-kibana:v1
    ports: []
    volumes: []
    extends:
      file: docker-compose.yml
      service: kibana
    environment:
      - KONTENA_LB_MODE=http
      - KONTENA_LB_BALANCE=roundrobin
      - KONTENA_LB_INTERNAL_PORT=5601
      - KONTENA_LB_VIRTUAL_HOSTS=loki.leonidasoy.fi
      - "KONTENA_LB_CUSTOM_SETTINGS=redirect scheme https if !{ ssl_fc }"
    external_links:
      - external-loadbalancer-lb1
    secrets:
      - name: KONTENA_LB_BASIC_AUTH_SECRETS
        secret: BASIC_AUTH_FOR_KIBANA1
        type: env
```
