### ISSUE TITLE
kontena service show has incorrect `dns` for stackless services

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#1485]
#### `kontena service show redis`
```yaml
development/null/redis:
  stack: development/null
  status: deploying
  image: redis:latest
  revision: 1
  stateful: no
  scaling: 3
  strategy: ha
  deploy_opts:
    min_health: 0.8
  dns: null-redis.development.kontena.local
  net: bridge
  instances:
    null-redis-1:
      rev: 2016-12-05 11:38:06 UTC
      service_rev: 1
      node: core-02
      dns: redis-1.development.kontena.local
      ip: 10.81.128.6
      public ip: ...
      status: running
      exit code: 0
    null-redis-2:
      rev: 2016-12-05 11:38:06 UTC
      service_rev: 1
      node: core-01
      dns: redis-2.development.kontena.local
      ip: 10.81.128.22
      public ip: ...
      status: running
      exit code: 0
```

#### `dig +short @172.17.0.1 null-redis.development.kontena.local`

NXDOMAIN

#### `dig +short @172.17.0.1 redis.development.kontena.local`

This is the correct DNS name for the service.
