### ISSUE TITLE
Binding multiple IPs to a service fails with only one IP being used.

### ISSUE THREAD

**Issue by cooperaj** [kontena/kontena#1489]
Kontena: 1.0.0
Docker: 1.12.3

I'm attempting to setup a DNS server that will server both internal and external requests via partitioned views. Internal requests get internal IP addresses. External... external. I am only running a single dev host at this time put would use affinities to ensure this worked at a larger scale.

In order to allow the DNS server to run I have to bind it to an address so that it does not conflict with the weave DNS server. I have a `kontena.yml` file that looks something like

```
dns:
    image: cooperaj/bind9:latest
    environment:
      - COMMAND_OPTIONS=-f -g
    ports:
      - PUBLIC_IP:53:53/udp
      - PRIVATE_IP:53:53/udp
    volumes:
      - /srv/bind:/etc/bind
```

When this is installed and deployed I end up with a `docker ps` that looks like

```
06c70d68a578        cooperaj/bind9:latest        "/init.sh"               56 seconds ago      Up 56 seconds       PRIVATE_IP:53->53/udp   hungry_newton
```

If I switch the order of the port definitions I have something that looks like

```
06c70d68a578        cooperaj/bind9:latest        "/init.sh"               56 seconds ago      Up 56 seconds       PUBLIC_IP:53->53/udp   hungry_newton
```

If I run a direct docker command on the host like

```
docker run --rm -it -p PUBLIC_IP:53:53/udp -p PRIVATE_IP:53:53/udp -v /srv/bind:/etc/bind -e COMMAND_OPTIONS="-f -g" cooperaj/bind9:latest
```

I end up with 

```
06c70d68a578        cooperaj/bind9:latest        "/init.sh"               56 seconds ago      Up 56 seconds       PRIVATE_IP:53->53/udp, PUBLIC_IP:53->53/udp   hungry_newton
```

In the each of these cases it works exactly as you'd expect, either only responding on the interface that successfully gets bound or in the last case on both, as desired.
