### ISSUE TITLE
`stack build` should support $grid variable

### ISSUE THREAD

**Issue by colinmollenhour** [kontena/kontena#1501]
Without the $grid variable supported in yml files for `stack build` command the grid has to be hard-coded into the image url. Example:

```
stack: redis-cache
version: 0.5.1
expose: lb

services:

  lb:
    image: registry.$grid.kontena.local/redis-cache-lb:latest
    build:
      context: ./redis-lb
    depends_on:
      - server
    environment:
      - SERVICE_HOSTNAME=server
      - UPDATE_FREQUENCY=20
    instances: 1
    deploy:
      strategy: daemon
    affinity:
      - label==app

  server:
    image: redis:3.2-32bit
    command: redis-server --maxmemory 700mb --maxmemory-policy volatile-lru --maxmemory-samples 3
    stateful: true
    volumes:
      - redis-data:/data
    instances: 2
    deploy:
      strategy: ha
    affinity:
      - label==app

  sentinel:
    image: registry.$grid.kontena.local/redis-sentinel:latest
    build:
      context: ./redis-sentinel
    environment:
      - SERVICE_HOSTNAME=server
      - QUORUM=2
      - DOWN_AFTER=1000
    depends_on:
      - server
    instances: 3
    deploy:
      strategy: ha

```

It should not be required to manually replace `$grid` with a grid name, making the yml file which is otherwise reusable on any grid now have to be edited just for this one variable.

Alternatively bringing back `registry.kontena.local` might be a solution but I think just support the current grid name as the $grid variable would be simpler.
