### ISSUE TITLE
Stack YAML ${STACK} interpolates the stack file name, not the installed stack name

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#1504]
Current git master with #1475 seems to interpolate `${STACK}` within the YAML `variables` section.

Unfortunately, it only interpolates the `stack: ...` name from the YAML, which is almost useless. It should interpolate the `kontena stack install --name ...` :(

For example, with `kontena stack install --name wordpress-red wordpress/kontena.yml`, the resulting vault variable is `wordpress_wordpress-mysql-root`. It should be `wordpress-red_wordpress-mysql-root`.

This also needs to happen correctly for `kontena stack upgrade`.

## `wordpress/kontena.yml`
```yaml
variables:
  wordpress-mysql-root:
    type: string
    from:
      vault: ${STACK}_wordpress-mysql-root
      random_string: 32
    to:
      vault: ${STACK}_wordpress-mysql-root
```

#### `DEBUG=true kontena stack install --name wordpress-red .../wordpress/kontena.yml `
```
Running Kontena.run("vault read --return wordpress_wordpress-mysql-root", returning: result
Running Kontena.run("vault write --silent wordpress_wordpress-mysql-root ...", returning: status
```

#### `kontena service show wordpress-red/mysql`
```yaml
development/wordpress-red/mysql:
  stack: development/wordpress-red
  secrets: 
    - secret: wordpress_wordpress-mysql-root
      name: MYSQL_ROOT_PASSWORD
      type: env
```

#### `kontena vault ls`
```
NAME                                                   CREATED AT                UPDATED AT               
wordpress_wordpress-mysql-root                         2016-12-08T11:16:55.990Z  2016-12-08T11:16:55.990Z 
```
