### ISSUE TITLE
Stackfile interpolation breaks on foo-bar variables

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#1507]
Trying to use the following kind of variable name:

```yaml
variables:
  web-path:
    type: string
    ....
services:
  wordpress:
    environment:
      KONTENA_LB_VIRTUAL_PATH: ${web-path}
```

Results in the following service configuration:

```yaml
development/wordpress-red/wordpress:
  env: 
    - KONTENA_LB_VIRTUAL_PATH=-path}
```

The variables should be validated to match the `/\w+` used for interpolation, failing with an error otherwise.

Alternatively, the interpolation should be a bit smarter... leaving bits and pieces of the `}` hanging around looks ugly.
