### ISSUE TITLE
typo'd service affinity filters are ignored

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#1524]
```yaml
stack: terom/test
version: 0.0.1
services:
    test:
        image: debian:jessie
        command: echo test
        affinity:
            - nodes==core-02
```

kontena will happily deploy this service to the `core-01` node:

```
I, [2016-12-09T12:09:52.377488 #4893]  INFO -- GridServiceDeployer: deploying service instance development/test/test-1 to node core-01
```
