### ISSUE TITLE
Stack service context variables

### ISSUE THREAD

**Issue by kke** [kontena/kontena#1553]
In addition to the global variables definition, it could be handy to be able to define variables for a service inside that service's definition in the YAML.

Currently you're jumping back and forth when building a stack, perhaps namespacing the variables and creating repetitive branching logic.

It would probably be a bit cleaner to define service specific variables inside the definition of that service. 

It would avoid this:

```yaml
variables:
  use_bundled_pg:
    type: boolean

  bundled_pg_port:
    only_if: use_bundled_pg
  bundled_pg_username:
    only_if: use_bundled_pg

```

by allowing this:

```yaml
variables:
  use_bundled_pg:
    type: boolean

services:
  pg:
    only_if: use_bundled_pg
    variables:
      port:
        type: integer
      username:
        type: string
```

I think it would also have some benefits when including / requiring / extending stack services.
