### ISSUE TITLE
Share volume between services

### ISSUE THREAD

**Issue by jalberto** [kontena/kontena#1559]
I am trying to share a volume/dir between 2 services in same stack (rails & sidekiq).

1st I try this approach:

```
stack: t/foo

services:
  api:
    stateful: true
    afinity: something

  workers:
    afinity: something
    volumes_from: api
```

but I get this error on deploy:

```
 [done] Creating stack api      
 [fail] Deploying stack api     
        Cannot find applicable node for service instance grid/api/workers-1
```

If I define volumes in each service, they are ignored as kontena doesn't support volumes yet.

Whats the correct way?

**Comment by jakolehm** [comment]
Kontena supports local named volumes like this (volumes are created automatically):

```
services:
  rails:
    image: my/rails:latest
    volumes:
      - rails-data:/data

  sidekiq:
    image: my/rails:latest
    affinity:
      - service==rails
    volumes:
      - rails-data:/data
```

CLI/docs say that volumes are not supported because master still misses volume management api's.
