### ISSUE TITLE
Monitor not showing which nodes services are running on

### ISSUE THREAD

**Issue by counterbeing** [kontena/kontena#1608]
When I first jumped into Kontena, i started building my app as a `stack`. Having looked at the manual a bit more, I decided it might really fit in more as an `app`. So, I just made what I thought were the necessary adjustments, and began running my commands with app. It's nice that it gathers context from the current directory to make commands a bit shorter. But now, when I run the monitor command for the app I don't see which nodes things are running on. 

![image](https://cloud.githubusercontent.com/assets/239798/21598998/a0b6e404-d11a-11e6-9f86-020e1d808367.png)

Here's my `kontena.yml` file in case anything is suspect:

```yaml
---
version: '2'
name: rails_app
services:
  load_balancer:
    image: kontena/lb:latest
    deploy:
      strategy: daemon
    ports:
      - 443:443
      - 80:80
      - 9000:9000
    secrets:
      - secret: internal_cert
        name: SSL_CERTS
        type: env

  web:
    image: registry.production.kontena.local/production:latest
    instances: 2
    deploy:
      wait_for_port: 9292
    environment:
      - KONTENA_LB_HEALTH_URI=/status
      - KONTENA_LB_MODE=http
      - KONTENA_LB_BALANCE=roundrobin
      - KONTENA_LB_INTERNAL_PORT=9292
      - KONTENA_LB_VIRTUAL_HOSTS=load_balancer.rails_prod.production.kontena.local
      - KONTENA_LB_CUSTOM_SETTINGS=redirect scheme https if !{ ssl_fc }
      - RAILS_ENV=production
    links:
      - load_balancer


  minio:
    stateful: true
    image: corylogan/minio-distributed-kontena
    instances: 3
    command: /entrypoint.sh
    secrets:
      - secret: MINIO_ACCESS_KEY
        name: MINIO_ACCESS_KEY
        type: env
      - secret: MINIO_SECRET_KEY
        name: MINIO_SECRET_KEY
        type: env
    environment:
      - KONTENA_LB_MODE=http
      - KONTENA_LB_BALANCE=roundrobin
      - KONTENA_LB_INTERNAL_PORT=9000
      - KONTENA_LB_VIRTUAL_HOSTS=minio.rails_prod.production.kontena.local
    links:
      - load_balancer
```
