### ISSUE TITLE
Upgrading a stack does not change values

### ISSUE THREAD

**Issue by counterbeing** [kontena/kontena#1659]
Kontena version 1.0.5

I just attempted to make a change to my stack by removing the `wait_for_port`. I upgraded the stack using `kontena stack upgrade rails kontena-rails.yml`.

But then running `kontena stack show rails` returns:

```
    web:
      image: corylogan/my-repo:latest
      status: running
      revision: 19
      stateful: no
      scaling: 7
      strategy: random
      deploy_opts:
        min_health: 0.8
      wait_for_port: 9292
      dns: web.rails.prod.kontena.local
      links:
        - lb/lb => prod/lb/lb
```

As you can see, `wait_for_port` persisted.

I also then tried just changing the value, thinking the bug might just apply to removal, and not changing. After changing the `wait_for_port` value to `9000`, it still returns `9292` as it was originally in my `kontena-rails.yml` file. 

The upgrade operation returns success. Are these values persisted in etcd? Am I misunderstanding how the process is supposed to work?
