### ISSUE TITLE
Skip creating service for "parent" service.

### ISSUE THREAD

**Issue by colinmollenhour** [kontena/kontena#1682]
In a few cases I like to use a "base" service to define common parameters and "extends: service: base" to extend this base service. However, when deploying the stack now there is an extraneous "base" service that is not actually used anywhere. Is there already a way to mark this service as one that should not actually be instantiated when the stack is deployed?

For example something like this:

```
stack: test
version: 0.5.0
services:
  base:
    abstract: true       <-- or some other key/value to indicate not a real service
    image: redis:3.2-32bit
    deploy:
      strategy: ha

  child:
    extends: base
    command: redis-server --maxmemory 700mb --maxmemory-policy volatile-lru
    instances: 1
```

```
$ kontena stack install test.yml
$ kontena service ls
NAME
test/child
test/base  <--- This should not exist
```

**Comment by jnummelin** [comment]
Not sure if you figured this out yet, but it is possible already. You just have to define the "abstract" base service(s) in another stack file. So something like this:
```
--- base.yml
stack: jussi/web
description: Web A
version: 0.0.1
services:
  web:
    image: nginx
    environment:
      - FOO=bar


--- extends.yml
stack: jussi/extended
description: Extended service
version: 0.0.1
services:
  extended:
    extends:
      file: base.yml
      service: web
```
