### ISSUE TITLE
ImagePullWorker pulls non-stop

### ISSUE THREAD

**Issue by matti** [kontena/kontena#1731]
With 1.1.0.rc1

kontena-lb deployed with stack:
```
stack: matti/lb-ingress
version: 0.1.0
expose: lb
variables:
  lb_stats_password:
    type: string
    from:
      vault: LB_INGRESS_STATS_PASSWORD
      random_string: 12
    to:
      vault: LB_INGRESS_STATS_PASSWORD
services:
  lb:
    image: kontena/lb:latest
    ports:
      - 80:80
      - 443:443
    affinity:
      - label==lb-ingress
    deploy:
      strategy: daemon
      wait_for_port: 80
      interval: 1h
    health_check:
      protocol: http
      port: 80
      uri: /__health
    environment:
      - KONTENA_LB_HEALTH_URI=/__health
    secrets:
      - secret: LB_INGRESS_STATS_PASSWORD
        name: STATS_PASSWORD
        type: env
```

Causes (?) this (see timestamps):

```
$ kontena grid logs -t | grep ImagePullWorker
kontena-agent | I, [2017-01-29T20:45:50.932935 #1]  INFO -- Kontena::Workers::ImagePullWorker: pulling image: kontena/lb:latest
kontena-agent | I, [2017-01-29T20:45:52.066893 #1]  INFO -- Kontena::Workers::ImagePullWorker: pulled image: kontena/lb:latest
kontena-agent | I, [2017-01-29T20:46:04.737800 #1]  INFO -- Kontena::Workers::ImagePullWorker: pulling image: kontena/lb:latest
kontena-agent | I, [2017-01-29T20:46:05.797409 #1]  INFO -- Kontena::Workers::ImagePullWorker: pulled image: kontena/lb:latest
kontena-agent | I, [2017-01-29T20:46:06.431687 #1]  INFO -- Kontena::Workers::ImagePullWorker: pulling image: kontena/lb:latest
kontena-agent | I, [2017-01-29T20:46:07.497297 #1]  INFO -- Kontena::Workers::ImagePullWorker: pulled image: kontena/lb:latest
kontena-agent | I, [2017-01-29T20:46:24.923399 #1]  INFO -- Kontena::Workers::ImagePullWorker: pulling image: kontena/lb:latest
kontena-agent | I, [2017-01-29T20:46:26.165511 #1]  INFO -- Kontena::Workers::ImagePullWorker: pulled image: kontena/lb:latest
kontena-agent | I, [2017-01-29T20:46:26.625723 #1]  INFO -- Kontena::Workers::ImagePullWorker: pulling image: kontena/lb:latest
kontena-agent | I, [2017-01-29T20:46:27.744637 #1]  INFO -- Kontena::Workers::ImagePullWorker: pulled image: kontena/lb:latest
```
