### ISSUE TITLE
Expose the number of instances as an environmental variable

### ISSUE THREAD

**Issue by panuhorsmalahti** [kontena/kontena#1732]
The current instance number is already exposed as `KONTENA_SERVICE_INSTANCE_NUMBER`. It would be useful to expose the total number of instances as e.g. `KONTENA_SERVICE_INSTANCES`. 

Using these two numbers one instance could connect to all the other instances of the same type (by iterating from 1 to KONTENA_SERVICE_INSTANCES and skipping the instance's own number). This is useful for e.g. broadcasting a message for all the other instances without using some kind of extra message queue or similar system.

**Comment by SpComb** [comment]
> It would be useful to expose the total number of instances as e.g. `KONTENA_SERVICE_INSTANCES`.

Using an environment variable for this runs into the problem of what happens to existing service instances if you scale a service up/down: do you re-deploy all of the existing instances just to update their `KONTENA_SERVICE_INSTANCES=` env?

**Comment by SpComb** [comment]
One approach is to use the service-level DNS within the service containers for this kind of thing:

```
$ docker exec -it null-redis-1 getent hosts redis
10.81.128.39    redis.development.kontena.local
10.81.128.28    redis.development.kontena.local
10.81.128.112   redis.development.kontena.local
10.81.128.110   redis.development.kontena.local
```

Those DNS lookups will change over time as service containers are being deployed etc.

**Comment by kke** [comment]
In 1.1 there's this: #1678

You can send that to the container's env by doing:

```yaml
variables:
  redis_instances:
    type: integer
    default: 1
    from: 
      service_instances: redis
services:
  redis:
    image: redis:latest
    instances: $redis_instances
  app:
    image: app:latest
    environment: 
      - "REDIS_INSTANCES=$redis_instances"
```
