### ISSUE TITLE
stack conditionals how do they work?

### ISSUE THREAD

**Issue by matti** [kontena/kontena#1786]
I'm trying to understand how `only_if` works: I just don't get it and to me it seems buggy:

```
stack: optowat
version: 0.0.1

variables:
  yes_or_no:
    type: boolean
    default: true
    from:
      prompt:

  wat:
    type: string
    from:
      prompt:

  test1:
    type: string
    only_if:
      - wat=lol
    from:
      prompt: "only if wat==lol (never called)"

  test2:
    type: string
    only_if: yes_or_no
    from:
      prompt: "I'm always shown!"

services:
  alpine:
    image: alpine
```

**Comment by matti** [comment]
Are they supposed to work? I don't think these work at all:

```
  deploy_hubot:
    type: boolean
    from:
      prompt: Deploy hubot chat bot?
  bot_name:
    only_if: deploy_hubot
    type: string
    default: bot
    from:
      prompt: Enter a nick name for hubot
```

Runs:

```
$ kontena stack install kke/rocketchat

> Use bundled Mongo? : Yes
> Hubot listens on all public channels? : Yes
**> Deploy hubot chat bot? : no**
> Enter SMTP uri : smtp://smtp.example.com
**> Enter a nick name for hubot : (bot)** 
```

**Comment by jakolehm** [comment]
It seems that `type: boolean` does return value as a string by default.. You can workaround this by defining `as: boolean`.

**Comment by jakolehm** [comment]
Example:

```
  deploy_hubot:
    type: boolean
    as: boolean
    from:
      prompt: Deploy hubot chat bot?
  bot_name:
    only_if: 
      deploy_hubot: true
    type: string
    default: bot
    from:
      prompt: Enter a nick name for hubot
```
