### ISSUE TITLE
Stack array picking should show more values than 6

### ISSUE THREAD

**Issue by matti** [kontena/kontena#1793]
stack variable:
```
  lb_certs:
    type: array
    required: false
    from:
      vault_cert_prompt: Pick SSL cert(s) from Vault
```

Gives this with Let's encrypt:
```
> Pick SSL cert(s) from Vault ....
  ⬡ LE_CERTIFICATE_app1_dot_com_PRIVATE_KEY
  ⬡ LE_CERTIFICATE_app1_dot_com_CERTIFICATE
  ⬢ LE_CERTIFICATE_app1_dot_com_BUNDLE
‣ ⬡ LE_CERTIFICATE_app2_org_PRIVATE_KEY
  ⬡ LE_CERTIFICATE_app2_org_CERTIFICATE
  ⬢ LE_CERTIFICATE_app2_org_BUNDLE
(Move up or down to reveal more choices)
```

since there are always 3 vault keys per domain, having a limit of 6 is kind of small (2 domains visible) -- maybe also the `(Move up or down..)` could somehow indicate how many more there are. I didn't understand right away that you could scroll down, I thought my certs had gone missing.
