### ISSUE TITLE
Stack variable type "password"

### ISSUE THREAD

**Issue by matti** [kontena/kontena#1794]
```
variables:
  registry_htpasswd_password:
    type: string
    from:
      prompt:
```

something that would not echo to the screen would be nice
