### ISSUE TITLE
Support for managed volumes

### ISSUE THREAD

**Issue by jnummelin** [kontena/kontena#1803]
Kontena should support named volumes as top level concept in stack yaml. This naturally also means that volumes are then "schedulable" objects.

Below is crude list of things needed:
- Yaml parser needs to support volumes
- Master has volumes API (CRUD)
- Migration picks up named volumes from existing services
- Agent sends available volume drivers to master
    - Master can use this info when scheduling services using volumes

Volumes definition follows docker-compose [syntax](https://docs.docker.com/compose/compose-file/#/volume-configuration-reference):

```
volumes:
  data:
    scope: instance-shared
    driver: rexray
    driver_opts:
      foo: bar
      baz: 1
```

Volumes can be defined in three modes: `instance-shared`, `instance-private` or `node`

### instance-shared

```
# Volume shared between web and sidekick
# web-1, sidekick-1 shares vol-1
# web-2, sidekick-2 shares vol-2
services:
  web:
    stateful: true
    volumes:
      - vol


  sidekick:
    volumes:
      - vol

volumes:
  vol:
    scope: instance-shared
    driver: ebs
```

So there will be a volume created per instance of the service that uses the volume. Also different service instances will be able to share the same volumes. This implies also service affinity between the services sharing the volumes in this mode.

### instance-private
```
# All instances get their own volume
# web-1, web-vol-1
# sidekick-1 sidekick-vol-1
# web-2, web-vol-2
# sidekick-2, sidekick-vol-2
# Deployment fails if trying to share "vol"
services:
  web:
    stateful: true
    volumes:
      - vol

  sidekick:
    volumes:
      - vol

volumes:
  vol:
    scope: instance-private
```

All service instances will get their own volume created during deploy.

### node

```
# Only one volume per node
# web-1 -> vol
# sidekick-1 -> vol
# web-2 -> vol
# sidekick-2 -> vol
services:
  web:
    stateful: true
    volumes:
      - vol

  sidekick:
    volumes:
      - vol

volumes:
  vol:
    scope: node
```

In this mode only one volume will be created per node and many services can use the same volume. A volume is created only on the nodes where the referencing services are deployed to.

**Comment by matti** [comment]
in kontena `instance` is used as "container instance", not as "vm instance"

**Comment by jnummelin** [comment]
My first gut feeling was that volumes should be global. So if one stack defines volume `xyz`, any other stack can use that automatically.

Are there any real use cases where one would expect a volume to be stack scoped? With stack scoped I mean that it can be referenced only by services within the same stack. If they would be stack "scoped", would there be use cases where a volume must be shared between stacks? If yes, it gives couple of options.

They could be always still included in the stack yaml, same way as in docker-compose:
```
stack: stack A
services:
   svc-a:
      image: redis
      volumes:
         - volX:/data
volumes:
   volX:
      external: otherStack/vol-foo
```

Or the reference could be bundled in the service which uses other stacks volumes:
```
stack: stack A
services:
   svc-a:
      image: redis
      volumes:
         - stackB/volX:/data
```
