### ISSUE TITLE
Services in stack fail to deploy when using volumes_from

### ISSUE THREAD

**Issue by cooperaj** [kontena/kontena#1808]
Version: **1.1.0** (master, agent and CLI)

I have the following stack file:
```
stack: web
version: 0.1.0

services:

  nginx:
    image: cooperaj/nginx:latest
    instances: 1
    deploy:
      strategy: ha
      wait_for_port: 80
    affinity:
      - label==region=lon1
    environment:
      - KONTENA_LB_MODE=http
      - KONTENA_LB_BALANCE=roundrobin
      - KONTENA_LB_INTERNAL_PORT=80
      - KONTENA_LB_VIRTUAL_HOSTS=test.example.com
    links:
      - php
      - ingress/http-lb
    volumes_from:
      - "web.src-%%s"

  php:
    image: cooperaj/php:7.1-fpm-alpine
    instances: 1
    deploy:
      strategy: ha
      wait_for_port: 9000
    affinity:
      - label==region=lon1
    volumes_from:
      - "web.src-%%s"

  src:
    image: alpine:latest
    command: /bin/sleep 86400
    affinity:
      - label==region=lon1
    volumes:
      - /srv/web:/srv
```

When deploying this stack **only** the _src_ service gets deployed. Inspecting the stack shows it as `partially_running` with the _php_ and _nginx_ services showing as `initialized`.

The logs for **kontena-server-api** shows

```
I, [2017-02-07T16:13:44.466016 #6]  INFO -- StackDeployWorker: skipping deployment of production/web/php because it will be deployed by dependencies
I, [2017-02-07T16:13:44.470523 #6]  INFO -- StackDeployWorker: skipping deployment of production/web/nginx because it will be deployed by dependencies
```

The dependencies don't ever appear to get around to deploying them.
