### ISSUE TITLE
stack variable service_link errors with empty prompt

### ISSUE THREAD

**Issue by matti** [kontena/kontena#1845]
works:
```
  lb_service:
    type: string
    from:
      service_link:
        prompt: Pick a loadbalancer
        image: kontena/lb
```

explodes:
```
  lb_service:
    type: string
    from:
      service_link:
        prompt:
        image: kontena/lb
```

**Comment by jnummelin** [comment]
How does it explode?

I failed to reproduce:
```
$ k stack install ~/code/stacks/link-resolver.yml 
 [error] Resolver 'service_link' for 'lb_link' : prompt missing
```

the stack:
```
variables:
  lb_link:
    type: string
    required: true
    default: socket/lb
    from:
      service_link:
        prompt:
        image: kontena/lb
```

**Comment by matti** [comment]
try with this:

```
stack: matti/pgweb
version: 0.0.1
description: sosedoff/pg-web

variables:
  affinity:
    type: string
    default: label!=no-pgweb
    from:
      prompt:
  lb_service:
    type: string
    from:
      service_link:
        prompt:
        image: kontena/lb
  lb_domain:
    type: string
    default: pgweb.example.net
    from:
      prompt:

services:
  web:
    image: sosedoff/pgweb:latest
    deploy:
      wait_for_port: 8081
      interval: 1d
    health_check:
      protocol: http
      port: 8081
      interval: 60
      uri: /
      initial_delay: 60
      timeout: 2
    affinity:
      - {{ affinity }}
    environment:
      - KONTENA_LB_INTERNAL_PORT=8081
      - KONTENA_LB_VIRTUAL_HOSTS={{ lb_domain }}
      - KONTENA_LB_CUSTOM_SETTINGS=redirect scheme https if !{ ssl_fc }
    links:
      - {{ lb_service }}
```

**Comment by jnummelin** [comment]
```
kontena stack install --no-deploy pgweb.yml 
> Enter affinity : label!=no-pgweb
 [error] Resolver 'service_link' for 'lb_service' : prompt missing
         Rerun the command with environment DEBUG=true set to get the full exception
```

**Comment by matti** [comment]
so it explodes, right?

whereas

```
  affinity:
    type: string
    default: label!=no-pgweb
    from:
      prompt:
```

just says `> Enter affinity : (label!=no-pgweb)`
