### ISSUE TITLE
Referencing a non-existing stack variable error is hard to understand

### ISSUE THREAD

**Issue by matti** [kontena/kontena#1846]
```
 [error] undefined method `match' for nil:NilClass
Did you mean?  catch
```

**Comment by kke** [comment]
What kind of yml does this come from? It should say "Undeclared variable 'foo' ...." if you're trying to use an unknown one.

**Comment by matti** [comment]
see `affinitylol` in this stack:

```
stack: matti/pgweb
version: 0.0.1
description: sosedoff/pg-web

variables:
  affinity:
    type: string
    default: label!=no-pgweb
    from:
      prompt:
  lb_service:
    type: string
    from:
      service_link:
        prompt: Pick a loadbalancer
        image: kontena/lb
  lb_domain:
    type: string
    default: pgweb.example.net
    from:
      prompt:

services:
  web:
    image: sosedoff/pgweb:latest
    deploy:
      wait_for_port: 8081
      interval: 1d
    health_check:
      protocol: http
      port: 8081
      interval: 60
      uri: /
      initial_delay: 60
      timeout: 2
    affinity:
      - {{ affinitylol }}
    environment:
      - KONTENA_LB_INTERNAL_PORT=8081
      - KONTENA_LB_VIRTUAL_HOSTS={{ lb_domain }}
      - KONTENA_LB_CUSTOM_SETTINGS=redirect scheme https if !{ ssl_fc }
    links:
      - {{ lb_service }}
```

**Comment by SpComb** [comment]
It looks like the stackfile interpolation results in `nil` values for invalid liquid `{{ ... }}` variables:

```yaml
stack: test/variables
variables:
  asdf:
    type: string
    default: asdf
services:
  test:
    image: redis
    affinity:
      - {{ asdflol }}
```

Results in the following `Kontena::Cli::Stacks::YAML::Reader.fully_interpolated_yaml`:

```ruby
{"stack"=>"test/variables", "variables"=>{"asdf"=>{"type"=>"string", "default"=>"asdf"}}, "services"=>{"test"=>{"image"=>"redis", "affinity"=>[nil]}}}
```

The `nil` then explodes as if the YAML had `affinity: - null`:

```
NoMethodError: undefined method `match' for nil:NilClass
Did you mean?  catch
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/stacks/yaml/custom_validators/affinities_validator.rb:13:in `block in validate'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/stacks/yaml/custom_validators/affinities_validator.rb:13:in `each'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/stacks/yaml/custom_validators/affinities_validator.rb:13:in `find_all'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/stacks/yaml/custom_validators/affinities_validator.rb:13:in `validate'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/hash_validator-0.7.0/lib/hash_validator/validators/optional_validator.rb:14:in `validate'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/hash_validator-0.7.0/lib/hash_validator/validators/hash_validator.rb:21:in `block in validate'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/hash_validator-0.7.0/lib/hash_validator/validators/hash_validator.rb:20:in `each'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/hash_validator-0.7.0/lib/hash_validator/validators/hash_validator.rb:20:in `validate'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/hash_validator-0.7.0/lib/hash_validator/base.rb:28:in `validate'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/hash_validator-0.7.0/lib/hash_validator/base.rb:10:in `initialize'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/hash_validator-0.7.0/lib/hash_validator/base.rb:19:in `new'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/hash_validator-0.7.0/lib/hash_validator/base.rb:19:in `validate'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/hash_validator-0.7.0/lib/hash_validator.rb:3:in `validate'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/stacks/yaml/validations.rb:70:in `validate_options'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/stacks/yaml/validator_v3.rb:36:in `block in validate'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/stacks/yaml/validator_v3.rb:31:in `each'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/stacks/yaml/validator_v3.rb:31:in `validate'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/stacks/yaml/reader.rb:168:in `validate'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/stacks/yaml/reader.rb:125:in `execute'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/stacks/common.rb:64:in `stack_from_yaml'
  /home/kontena/kontena/kontena/cli/lib/kontena/cli/stacks/install_command.rb:23:in `execute'
  /home/kontena/kontena/kontena/cli/lib/kontena/command.rb:191:in `run'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
  /home/kontena/kontena/kontena/cli/lib/kontena/command.rb:191:in `run'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/clamp-1.1.2/lib/clamp/subcommand/execution.rb:11:in `execute'
  /home/kontena/kontena/kontena/cli/lib/kontena/command.rb:191:in `run'
  /home/kontena/kontena/kontena/cli/vendor/bundle/ruby/2.3.0/gems/clamp-1.1.2/lib/clamp/command.rb:132:in `run'
  bin/kontena:16:in `<top (required)>'
```
