### ISSUE TITLE
stack variable boolean default does not matter for prompt

### ISSUE THREAD

**Issue by matti** [kontena/kontena#1854]
```
  mongodb_lock:
    type: boolean
    default: false
    from:
      prompt:
```

results in:

```
> Enable mongodb_oplog : (Y/n)
```

when it should say:

```
> Enable mongodb_oplog : (y/N)
```
