### ISSUE TITLE
Stack deploy hangs in "Waiting for deployment to start" if the deployed service is in restart loop

### ISSUE THREAD

**Issue by matti** [kontena/kontena#1866]
Will prob. get fixed with 1.2 (?)

**Comment by SpComb** [comment]
A stack service stuck in a Docker restart loop does allow you to deploy it on 1.2-dev. Needs better repro case if this is something more complicated. 

```yaml
stack: test/test
services:
  bar:
    image: debian:jessie
    command: /bin/false
```

That shows up as `restarting`:

```
  created: 2017-03-29T14:12:14.498Z
  updated: 2017-03-29T14:12:14.498Z
  stack: development/test
  state: running
  image: debian:jessie
  revision: 1
  stack_revision: 1
  stateful: no
  scaling: 1
  strategy: ha
  deploy_opts:
    min_health: 
  dns: bar.test.development.kontena.local
  cmd: /bin/false
  net: bridge
  instances:
    test.bar-1:
      rev: 2017-03-29 14:12:14 UTC
      service_rev: 1
      node: core-02
      dns: bar-1.test.development.kontena.local
      ip: 10.81.128.25
      public ip: 82.181.164.219
      status: restarting
      exit code: 1
```

A stack deploy works:

```
 [done] Triggering deployment of stack test     
 [done] Waiting for deployment to start     
 [done] Deploying service bar     
```
