### ISSUE TITLE
stack prompt to fill variables from vault

### ISSUE THREAD

**Issue by matti** [kontena/kontena#1867]
``` 
admin_users:
    type: string
    from:
      vault: ${STACK}_DRONE_ADMIN_USERNAMES
      prompt: Admin usernames (comma separated)
    to:
      vault: ${STACK}_DRONE_ADMIN_USERNAMES
```

Currently prompt is not displayed on second deploy because vault has been updated. It would be handy to somehow still prompt with prefilled variables.
