### ISSUE TITLE
Support for environments in kontena.yml (feature proposal)

### ISSUE THREAD

**Issue by jalberto** [kontena/kontena#1868]
Using a pattern similar to Rails, Sidekiq, etc we can have a really flexible way to define stacks, eg:

```
service:
    foo:
        image: foo:staging
        instances: 1
production:
    service:
        foo:
          image: foo:latest
          instances: 3
```

`kontena upgrade` will save the full template and on `kontena deploy` ti will be compiled

This will allow `KONTENA_ENV=production kontena deploy foo' in a CI/CD system and `kontena deploy foo` run by hand by dev without conflicts

Currently to achieve somethign like this there is 2 ways:

1. duplicate each stack (so more lines ot mantain and proably noise in kontena commands)
2. use liquid template and run `konetena upgrade --deploy foo' each time, in both, CI?CD environment and dev wrokstation (this can be very error prune even get some race condition)
