### ISSUE TITLE
stack string default is not prompted if boolean

### ISSUE THREAD

**Issue by matti** [kontena/kontena#1875]
```
variables:
  gf_allow_sign_up:
    type: string
    default: "false"
    from:
      prompt:
```

prompts with default "false"

```
variables:
  gf_allow_sign_up:
    type: string
    default: false
    from:
      prompt:
```

prompts without default.

bug or "yaml feature" ?
