### ISSUE TITLE
stack service_link does not remember old selection

### ISSUE THREAD

**Issue by matti** [kontena/kontena#1888]
```
  lb_service:
    type: string
    required: false
    from:
      service_link:
        prompt: Pick a loadbalancer
        image: kontena/lb
```

Subsequent updates always default to "none"
