### ISSUE TITLE
can not remove "partially_running" stack

### ISSUE THREAD

**Issue by matti** [kontena/kontena#1928]
The stack state is "partially_running" and it has just one service that's "0 / 1      no       deleting"

Tried stopping, rm --forceing, redeploying...

Maybe caused by missing image (typo in `image:`)

**Comment by jakolehm** [comment]
#1873 should fix this.

**Comment by SpComb** [comment]
#1873 scheduler rewrite is merged for 1.2.0. Remove of a `partially_running` stack works as expected:

### `kontena stack show test`
```
test:
  created: 2017-03-29T13:45:53.733Z
  updated: 2017-03-29T13:45:53.736Z
  state: partially_running
  stack: test/test
  version: 0.0.1
  revision: 1
  expose: -
  services:
    foo:
      created: 2017-03-29T13:45:53.837Z
      updated: 2017-03-29T13:45:53.837Z
      image: redis:latest
      revision: 1
      state: running
      stateful: no
      scaling: 1
      strategy: ha
      deploy_opts:
        min_health: 
      dns: foo.test.development.kontena.local
    bar:
      created: 2017-03-29T13:45:53.861Z
      updated: 2017-03-29T13:45:53.861Z
      image: redis:nonexist
      revision: 1
      state: stopped
      stateful: no
      scaling: 1
      strategy: ha
      deploy_opts:
        min_health: 
      dns: bar.test.development.kontena.local
```

### `kontena stack rm test`
```
Destructive command. To proceed, type "test" or re-run this command with --force option.
> Enter 'test' to confirm:  test
 [done] Removing stack test      
```


### `kontena-agent`
```
I, [2017-03-29T14:00:02.599285 #1]  INFO -- Kontena::ServicePods::Terminator: terminating service: /test.foo-1
```
