### ISSUE TITLE
(stack variables) can not set empty value if a default is set

### ISSUE THREAD

**Issue by matti** [kontena/kontena#1933]
```
  lb_affinity:
    type: string
    default: label==lb-ingress
    from:
      prompt: Affinity
```

workaround: `strip: true` and give a space

**Comment by matti** [comment]
or
```
variables:
  lb_default_or_custom:
    type: enum
    options:
      - lb_ingress
      - custom
    from:
      prompt: "Select LB Affinity"
  lb_affinity_ingress:
    only_if:
      lb_default_or_custom: lb_ingress
    type: string
    value: "label==lb-ingress"
    to:
      env: lb_affinity

  lb_affinity_custom:
    only_if:
      lb_default_or_custom: custom
    type: string
    from:
      prompt: "Enter custom lb affinity"
    to:
      env: lb_affinity

  lb_affinity:
    type: string
    from:
      env: lb_affinity
```

by the infamous @kke

**Comment by kke** [comment]
I made an issue to tty-prompt for changing the behavior of default values in `ask` prompts: https://github.com/piotrmurach/tty-prompt/issues/45

**Comment by kke** [comment]
There could also be some kind of `prompt` thing for the skip_if:

```yaml
variables:
  lb_affinity:
    skip_if:
      prompt: "Use LB-affinity?"
    default: foofoo
    from:
      prompt: Foofoofoo
```

**Comment by kke** [comment]
Magic:

```yaml
---
stack: foo
variables:
  affinity:
    type: enum
    required: false
    can_be_other: true
    options:
      - label==lb-ingress
    from: prompt

services:
  baz:
    # {% if affinity %}
    affinity:
      - ${affinity}
    # {% endif %}
    image: foofoo
```

```
$ kontena stack validate foo.yml
> Select affinity :
  1: label==lb-ingress
‣ 2: (Other)
> Select affinity :
```
