### ISSUE TITLE
stack deploy fails due to missing service that is not missing

### ISSUE THREAD

**Issue by pcornelissen** [kontena/kontena#1958]
I recreated my staging grid and now I get an error when I try to install my stack:

```
# kontena stack install -n staging
 [fail] Creating stack staging
 [error] {"services"=>"Service create failed for service 'restaurants-host': Service staging/contactme-host does not exist"}
```

The kontena yaml contains the requested service of course:

```
services:
....
  contactme-host:
    extends:
      file: common-kontena.yaml
      service: java-service
    image: "nexus-dockerkulinariweb.orchit-dev.de/kulinariweb/contactme:${STAGE}_LATEST"
    depends_on:
      - eureka
      - confighub
      - rabbitmq
      - redis
      - dbinit
    links:
      - mariadb/node:mariadb
...
  restaurants-host:
    extends:
      file: common-kontena.yaml
      service: java-service
    image: "nexus-dockerkulinariweb.orchit-dev.de/kulinariweb/restaurants:${STAGE}_LATEST"
    depends_on:
      - eureka
      - rabbitmq
      - confighub
      - contactme-host
    links:
      - mariadb/node:mariadb
....
```
The services are created and in the initialized state. A kontena stack deploy afterwards seems to work. (still running)

**Comment by SpComb** [comment]
With a bit of logging, it looks like the server `Stack::SortHelper` is getting confused by the `sort_services(GridService)` vs `sort_services({services: [ ... ]}[:services])` variations in the `links` structure:

When called from `Stacks::Create` with the hash variant:

```
sort_services <- ["redis-before", "redis", "redis-after"]
sort_services a=redis links=[] <=> b=redis-after links=[{"name"=>"redis", "alias"=>"redis"}]
sort_services a=redis-before links=[{"name"=>"redis", "alias"=>"redis"}] <=> b=redis links=[]
sort_services a=redis-before links=[{"name"=>"redis", "alias"=>"redis"}] <=> b=redis-after links=[{"name"=>"redis", "alias"=>"redis"}]
sort_services -> ["redis", "redis-before", "redis-after"]
```

When called from `StackRemoveWorker` with the `GridService` model variant:

```
sort_services <- ["redis-before", "redis", "redis-after"]
sort_services a=redis links=[] <=> b=redis-after links=[{:name=>"redis"}]
sort_services a=redis-before links=[{:name=>"redis"}] <=> b=redis links=[]
sort_services a=redis-before links=[{:name=>"redis"}] <=> b=redis-after links=[{:name=>"redis"}]
sort_services -> ["redis", "redis-before", "redis-after"]
```

The `links` is `{ :name => ... }` vs `{ "name" => ... }`, and the implementation only works with the former, as used in the stack remove case...

**Comment by SpComb** [comment]
I think what's happening here is that one of your linked stack services has some invalid attributes (such as a `depends_on: ` referring to itself) which causes it to fail to be created. However, the server continues creating the remaining services, and then overwrites the actual error with this confusing error from the service that was linking to the service that actually failed to create.

**Comment by SpComb** [comment]
Assuming that the `staging/contactme-host` service failed to create for some reason, and then that cascaded to the `restaurants-host` service failing to create, then #1976 should fix the error handling, and also return the actual error that caused the `staging/contactme-host` service create to fail.

Assuming that the underlying error was caused by some service in the stack linking to itself, then #1976 should also fix that to return an `Linked service '...' refers to self` error.

**Comment by pcornelissen** [comment]
The contactme-host has been initialized and deploy of the whole stack works fine. I just have to start the deploy manually

**Comment by SpComb** [comment]
Odd, the `Service create failed for service 'restaurants-host': ...` should indicate that the `restaurants-host` service should not exist.

Can you provide the full stack file somehow? You must have some complex linking structure that is confusing the server if this is happening every time with Kontena 1.1.

**Comment by SpComb** [comment]
It seems the server's stack service sorting algorithm does get confused by appropriately complex stack service linking schemes... presumably when a service `bar` links to a `foo` later in the stack file, which then in turn links to a service `asdf` that has more links than either of `foo` or `bar`... The associated `kontena stack install` and `kontena stack rm` depend on the exact ordering of the services in the stackfile.

Repro case:

```yaml
stack: test/test
services:
  bar:
    image: redis
    depends_on:
      - foo

  foo:
    image: redis
    depends_on:
      - asdf

  asdf:
    image: redis
    depends_on:
      - asdf1
      - asdf2
      - asdf3
  asdf1:
    image: redis
  asdf2:
    image: redis
  asdf3:
    image: redis
```

With the error handling improvements in #1976:
```
 [fail] Creating stack test      
 [error] {"services"=>{"bar"=>{"links"=>"Service test/foo does not exist"}}}
```

In this case, the `test/bar` service is missing from `kontena service ls`. Changing the order of the services in the stack file may allow them to be created correctly, but may also results in associated `kontena stack rm` hangs as in #1836:

```
127.0.0.1 - - [15/Mar/2017:11:22:03 +0200] "DELETE /v1/stacks/development/test HTTP/1.1" 200 2 0.0869
E, [2017-03-15T11:22:03.742477 #32302] ERROR -- StackRemoveWorker: Cannot remove service development/test/asdf: {"service"=>"Cannot delete service that is linked to another service (foo)"}
E, [2017-03-15T11:22:05.795839 #32302] ERROR -- StackRemoveWorker: Cannot remove service development/test/asdf3: {"service"=>"Cannot delete service that is linked to another service (asdf)"}
E, [2017-03-15T11:22:05.813132 #32302] ERROR -- StackRemoveWorker: Cannot remove service development/test/asdf2: {"service"=>"Cannot delete service that is linked to another service (asdf)"}
E, [2017-03-15T11:22:05.832220 #32302] ERROR -- StackRemoveWorker: Cannot remove service development/test/asdf1: {"service"=>"Cannot delete service that is linked to another service (asdf)"}
```
