### ISSUE TITLE
Stack update does not validate volume configuration changes

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#2038]
Doing `kontena stack install` for a stack file will create a new `Volume` with the given options.

```yaml
volumes:
  grid-redis:
    scope: grid
    driver: local
```

Then doing a `kontena stack upgrade` with a modified stack file will accept but ignore any changed volume options.

```yaml
volumes:
  grid-redis:
    scope: instance
    driver: devnull
```

The server `Stacks::Update` mutation should fail validation if the volume options do not match the existing volumes, because the resulting stack volume will not reflect reality.
