### ISSUE TITLE
Server stack create does not validate volume options, leaves incomplete stack

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#2039]
Creating a stack with an invalid volume configuration that is missing a `driver` passes both CLI and server validation, but fails during execution, leaving a broken stack in place:

```yaml
stack: test/volumes
services:
  redis:
    image: redis:3.2
    instances: 1
    volumes:
      - redis:/data
volumes:
  redis:
    scope: instance
```

```
    *   Creating stack volumes1  .. \[API Client Request]: POST http://localhost:9292/v1/grids/development/stacks | Headers: {Accept: application/json, Content-Type: application/json, Authorization: Bearer}  | Body: 
{"name":"volumes1","stack":"test/volumes","expose":null,"version":"0.0.1","source":"stack: test/volumes\nservices:\n  redis:\n    image: redis:3.2\n    instances: 1\n    volumes:\n      - redis:/data\nvolumes:\n  redis:\n    scope: instance\n","registry":"file://","services":[{"instances":1,"image":"redis:3.2","links":[],"external_links":[],"ports":[],"volumes":["redis:/data"],"volumes_from":[],"affinity":[],"stateful":false,"deploy_opts":{"wait_for_port":null,"min_health":null,"interval":null},"hooks":{},"health_check":{"port":null,"protocol":null,"uri":null,"timeout":null,"interval":null,"initial_delay":null},"log_driver":null,"log_opts":null,"name":"redis"}],"volumes":[{"scope":"instance","name":"redis"}],"variables":{}}
    *   Creating stack volumes1  .. |[API Client Error]: 
D, [2017-03-31T14:02:27.377292 #20735] DEBUG -- CLIENT: Request POST /v1/grids/development/stacks: 422 Unprocessable Entity: {"error":{"volumes":{"redis":{"driver":"Driver is required"}}}}
 [fail] Creating stack volumes1      
{"volumes"=>{"redis"=>{"driver"=>"Driver is required"}}} {"volumes"=>{"redis"=>{"driver"=>"Driver is required"}}}
```

Fixing the stack file and trying to re-install fails:

```
D, [2017-03-31T14:02:33.075225 #20762] DEBUG -- CLIENT: Request POST /v1/grids/development/stacks: 422 Unprocessable Entity: {"error":{"name":"volumes1 already exists"}}
 [fail] Creating stack volumes1      
{"name"=>"volumes1 already exists"} {"name"=>"volumes1 already exists"}
```

The stack, and all of its services, do still get created, but the services seem to end up with an invalid `GridServiceVolume` that is missing the named volume?

```yaml
volumes2:
  created: 2017-03-31T11:06:23.467Z
  updated: 2017-03-31T11:06:23.470Z
  state: initialized
  stack: test/volumes
  version: 0.0.1
  revision: 1
  expose: -
  services:
    redis:
      created: 2017-03-31T11:06:23.483Z
      updated: 2017-03-31T11:06:23.483Z
      image: redis:3.2
      revision: 
      state: initialized
      stateful: no
      scaling: 1
      strategy: ha
      deploy_opts:
        min_health: 
      dns: redis.volumes2.development.kontena.local
      volumes:
        - /data
```
