### ISSUE TITLE
Cannot install multiple instances of stack using a stack volume name

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#2040]
Using a stackfile with some sub-stack scoped volume:

```yaml
stack: test/volumes
services:
  redis:
    image: redis:3.2
    instances: 1
    volumes:
      - redis3:/data
volumes:
  redis3:
    scope: instance
    driver: local
```

The same stackfile (or any other stackfile using the same volume name...) can only be installed once. Creating the second stack fails with:

```
D, [2017-03-31T14:09:43.821470 #21712] DEBUG -- CLIENT: Request POST /v1/grids/development/stacks: 422 Unprocessable Entity: {"error":{"volumes":{"redis3":{"name":"Volume with given name already exists"}}}}
 [fail] Creating stack volumes3b      
{"volumes"=>{"redis3"=>{"name"=>"Volume with given name already exists"}}} {"volumes"=>{"redis3"=>{"name"=>"Volume with given name already exists"}}}
```

The non-grid scoped `Volume`s created for each stack should be named with the stack instance name, so that multiple stacks (installed from the same or unrelated stackfiles) can be installed independently.
