### ISSUE TITLE
Stack files should not contain non-external grid-scope volumes

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#2041]
This breaks the desired stack isolation, because multiple stacks can't be created using the same grid-scope volume names, as the volume options can conflict between stacks.

```
stack: test/volumes-foo
services:
  foo:
    image: redis:3.2
    instances: 1
    volumes:
      - data:/data
volumes:
  data:
    scope: grid
    driver: local
```

The stack non-external volumes should be limited to `scope: stack` and above. Only `external: true` volumes should be `scope: grid`.
