### ISSUE TITLE
Service volume mounts with :ro breaks validation in 1.2.0

### ISSUE THREAD

**Issue by kke** [kontena/kontena#2219]
```yaml
services:
  foo:
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
     - /proc:/hostfs/proc:ro
     - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
     - /:/hostfs:ro
...
[errror]
volumes:
         ro: mount point defined 4 times
```
