### ISSUE TITLE
CLI: kontena grid update clears out default-affinity

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#2252]
If a grid has a default affinity set:

```
development:
  uri: ws://localhost:9292/
  initial_size: 1
  default_affinity: 
    - label!=special
  subnet: 10.81.0.0/16
  supernet: 10.80.0.0/12
  stats:
    nodes: 2 of 2
    cpus: 2
    load: 0.41 0.4 0.36
    memory: 0.94 of 1.95 GB
    filesystem: 8.11 of 31.14 GB
    users: 1
    services: 6
    containers: 98
```

Then a `kontena grid update` will wipe out that default affinity filter when updating any other parameter:

`DEBUG=api bundle exec bin/kontena grid update --log-forwarder fluentd --log-opt fluentd-address=127.0.0.1 development`
```
...
[API Client Request]: PUT http://localhost:9292/v1/grids/development | Headers: {Accept: application/json, Content-Type: application/json, Authorization: Bearer}  | Body: 
{"logs":{"forwarder":"fluentd","opts":{"fluentd-address":"127.0.0.1"}},"default_affinity":[]}
[API Client Response]: Headers: {Content-Type: application/json}  | Status: 200 | Body: 
{"id":"development","name":"development","token":"tB...0A==","initial_size":1,"stats":{"statsd":null},"default_affinity":[],"trusted_subnets":[],"node_count":2,"service_count":6,"container_count":98,"user_count":1,"subnet":"10.81.0.0/16","supernet":"10.80.0.0/12","logs":{"forwarder":"fluentd","opts":{"fluentd-address":"127.0.0.1"}}}
```

The default affinity is now gone from `kontena grid show`:
```
development:
  uri: ws://localhost:9292/
  initial_size: 1
  default_affinity: 
  subnet: 10.81.0.0/16
  supernet: 10.80.0.0/12
  stats:
    nodes: 2 of 2
    cpus: 2
    load: 0.41 0.4 0.36
    memory: 0.94 of 1.95 GB
    filesystem: 8.11 of 31.14 GB
    users: 1
    services: 6
    containers: 98
logs:
  forwarder: fluentd
  fluentd-address: 127.0.0.1
```

This is a bug in the CLI, where the `cli/grids/update_command.rb` conditional will always be true for the default `[]` value of the multi-valued `--default-affinity` parameter:

```ruby
      if default_affinity_list
        payload[:default_affinity] = default_affinity_list
      end
```
