### ISSUE TITLE
Fix flaky test in travis

### ISSUE THREAD

**Issue by jakolehm** [kontena/kontena#228]
```
Failures:

  1) Kontena::Pubsub.clear! removes all subscriptions
     Failure/Error: expect(described_class.subscriptions.size).to eq(0)
       
       expected: 0
            got: 1
       
       (compared using ==)
     # ./spec/lib/kontena/pubsub_spec.rb:39:in `block (3 levels) in <top (required)>'
```
