### ISSUE TITLE
Stack service "extends:" needs a way to ignore fields

### ISSUE THREAD

**Issue by kke** [kontena/kontena#2305]
For example:

```yaml
services:
  foo:
    extends:
      file: docker-compose.yml
      service: foo
```

Currently there's no way to unset / modify fields like env_file for example.

## option a

Add `reject` array to `extends` options.

## option b

Flip the `from.merge(service_config)` in `lib/kontena/cli/stacks/yaml/service_extender.rb` around, making it possible for the stack file to overwrite anything coming from the external file. (actually it needs to be `service_config.merge(from).merge(service_config['environment']).merge(service_config['secrets'])` and not just flip around)
