### ISSUE TITLE
Stack cannot upgrade with deleted linked services

### ISSUE THREAD

**Issue by jakubknejzlik** [kontena/kontena#2313]
When deploying changes to stack that contain deleting services which are linked together, the cli refuses to proceed, saying that it cannot delete service that is linked to another one.This is fine in case when I accidentally try to remove dependent service. But in case I want to remove both linked and linking services it should not be a problem.

# Example:

Deployed stack:

```
stack: test
services:
  test-web:
    image: dockercloud/quickstart-python
    links:
    - redis:redis
  redis:
    image: redis
```

Stack that needs to be deployed:
```
stack: test
services:
  test-web:
    image: hello-world
```

Error from cli:
```
 [fail] Upgrading stack test     
 [error] Kontena::Errors::StandardErrorHash : Unprocessable Entity:
	services:
	  redis:
	    service: Cannot delete service that is linked to another service (test-web)
```

This is caused by this PR https://github.com/kontena/kontena/pull/2128 

When the app validates removed services one by one with `GridServices::Delete.validate`. This approach isn't aware of the whole update process so it declines to delete `redis` without the knowledge that `test-web` is being deleted too.

Suggestions:
1) we can add option to specify `deletedServices` to `GridServices::Delete.validate`
2) we can "copy" the validation logic into the `Stacks::Update.validate` and update it to be aware of 
 that linked service is also deleted

Any thoughs? :)
