### ISSUE TITLE
 How to Configure Layer 7 reverse proxying using HA proxy and load balancing? 

### ISSUE THREAD

**Issue by santhoshkumarhirekerur** [kontena/kontena#2314]
How to Configure Layer 7 reverse proxying using HA proxy and load balancing? 
We want to have a single domain name that serves multiple applications, as the http requests can be analyzed to decide which application should receive the traffic.

**Comment by jnummelin** [comment]
```
stack: test/vhosts
version: 0.1.0
services:

  lb:
    image: kontena/lb
    ports:
      - 8888:80

  nginx:
    image: nginx:1-alpine
    links:
      - lb
    environment:
      - KONTENA_LB_VIRTUAL_HOSTS=foo.foobar.com
      - KONTENA_LB_VIRTUAL_PATH=/nginx

  web:
    image: httpd:alpine
    links:
      - lb
    environment:
      - KONTENA_LB_VIRTUAL_HOSTS=foo.foobar.com
      - KONTENA_LB_VIRTUAL_PATH=/apache

```
