### ISSUE TITLE
Stack YAML reader port validation NoMethodError

### ISSUE THREAD

**Issue by kke** [kontena/kontena#2322]
```
$ stack upgrade redis redis.yml
lib/kontena/cli/services/services_helper.rb:361:in `block in parse_ports': undefined method `split' for 6379:Integer (NoMethodError)
```

Of course the stack file used is invalid:

```yaml
services:
  redis:
    stateful: false
    image: redis:latest
    command: --appendonly yes --loglevel ${redis_log_level}
    ports:
      - 6379
```

but the error should be something more descriptive.

(seems like it doesn't happen in `stack validate`)
