### ISSUE TITLE
Iterate through variables in liquid

### ISSUE THREAD

**Issue by kke** [kontena/kontena#2431]
(converting to issue)

@matti commented 11 minutes ago in #2430:

Currently need to do this:

```yaml
# {% assign secrets = "REDIS_URL,MONGO_URL" | split: "," %}
# {% for secret in secrets %}
      - secret: ${STACK}_{{secret}}
        name: {{secret}}
        type: env
# {% endfor %}
```

With this could do:

```yaml
# {% for secret in VARIABLES | join: ',' %}
      - secret: ${STACK}_{{secret}}
        name: {{secret}}
        type: env
# {% endfor %}
```
