### ISSUE TITLE
Linking service from stack

### ISSUE THREAD

**Issue by GarPit** [kontena/kontena#2486]
Hello, guys.

Kontena is a great tool, very impressed by it but I have a question: is it possible to link basic Service (created separately via `kontena service create ...`) from Stack (kontena.yml)?

**Comment by SpComb** [comment]
You mean something like a `kontena/lb` service created outside of a stack? It would be recommended to run those as stacks for linking purposes, but you can also try using the undocumented `null` stack name to reference those:

```yaml
services:
  foo:
    links:
      - null/legacy-lb
```
