### ISSUE TITLE
stack validation errors are difficult to understand

### ISSUE THREAD

**Issue by matti** [kontena/kontena#2489]
```
 [error] Psych::SyntaxError : (<unknown>): did not find expected key while parsing a block mapping at line 6 column 3
```

Problem was in the indentation on line 57, not 6:

```
stack: influxdb
version: 0.0.1
expose: influxdb

variables:
  env:
    type: string
    default: devenv
    from:
      vault: ${STACK}_var_env
      env: XENV
      prompt:
    to:
      vault: ${STACK}_var_env

  PORT:
    type: integer
    default: 8080
    from:
      vault: ${STACK}_env_PORT
      env: XENV
      prompt:
    to:
      vault: ${STACK}_env_PORT

  lb_service:
    type: string
    required: false
    from:
      vault: ${STACK}_var_lb_service
      service_link:
        prompt: Pick a loadbalancer
        image: kontena/lb
    to:
      vault: ${STACK}_var_lb_service

  lb_https_redirect:
    only_if: lb_service
    type: boolean
    default: false
    from:
      vault: ${STACK}_var_lb_https_redirect_forwarded
      prompt: Force kontena/lb to redirect SSL if request is not SSL?
    to:
      vault: ${STACK}_var_lb_https_redirect_forwarded

  lb_https_redirect_forwarded:
    only_if: lb_service
    type: boolean
    default: false
    from:
      vault: ${STACK}_var_lb_https_redirect_forwarded
      prompt: Force kontena/lb to redirect SSL if header X-Forwarded-Proto is not https?
    to:
      vault: ${STACK}_var_lb_https_redirect_forwarded

   KONTENA_LB_VIRTUAL_HOSTS:
      only_if: lb_service
      type: string
      min_length: 1
      default: ${STACK}.${XENV_DOMAIN}
      from:
        vault: ${STACK}_env_KONTENA_LB_VIRTUAL_HOSTS
        prompt: KONTENA_LB_VIRTUAL_HOSTS

services:
  influxdb:
    image: "registry.example.com/${STACK}/web"
    deploy:
      strategy: ha
      interval: 1h
    stateful: true
    instances: 1
    environment:
      - KONTENA_LB_MODE=http
      - KONTENA_LB_INTERNAL_PORT={{ PORT }}
      - KONTENA_LB_VIRTUAL_HOSTS={{ lb_domain }}
      # {% if lb_https_redirect %}
      - KONTENA_LB_CUSTOM_SETTINGS=redirect scheme https if !{ ssl_fc }
      # {% endif %}
      # {% if lb_https_redirect_forwarded %}
      - KONTENA_LB_CUSTOM_SETTINGS=redirect scheme https if !{ hdr(X-Forwarded-Proto) -i https }
      # {% endif %}
    affinity:
# {% if env == 'devenv' or env == 'testenv' %}
      - label==env={{env}}
# {% endif %}
      - label!=ephemeral=yes
    volumes:
      - /var/lib/influxdb
```
