### ISSUE TITLE
Stack validate: [error] Psych::DisallowedClass : Tried to load unspecified class: Symbol

### ISSUE THREAD

**Issue by colinmollenhour** [kontena/kontena#2495]
Using latest 1.3.1 I tried to upgrade a stack and received the following error:

```
$ kontena stack validate kontena-redis-cache.yml
 [error] Psych::DisallowedClass : Tried to load unspecified class: Symbol
```

Here is my yaml file:

```
#
# Redis cache services
#
---
stack: redis-cache
version: 0.5.4
description: Redis cache services
expose: lb

variables:

  # Choose either custom registry or Kontena Grid Registry
  custom_registry:
    type: string
    from:
      vault: APP_REGISTRY
      prompt: Enter full repo URL or empty for Kontena Grid Registry
    to:
      env: registry
      vault: APP_REGISTRY
  kontena_registry:
    type: string
    skip_if: custom_registry
    from:
      interpolate: registry.${GRID}.kontena.local/magento
    to:
      env: registry
      vault: APP_REGISTRY

services:

  lb:
    image: ${registry}:redis-lb-latest
    build:
      context: ./redis/lb
    depends_on:
      - server
    environment:
      - SERVICE_HOSTNAME=server
      - UPDATE_FREQUENCY=20
      - FRONTEND_SOCKET_PATH=/run/magento/redis-cache.sock
    volumes:
      - run-magento:/run/magento
    instances: 1
    deploy:
      strategy: daemon
      min_health: 0.6
      wait_for_port: 6379
    affinity:
      - label==role=app

  server:
    image: ${registry}:redis-server-latest
    build:
      context: ./redis/server
    environment:
      - SENTINEL_HOSTNAME=sentinel
    command: redis-server --maxmemory 1024mb --maxmemory-policy volatile-lru --maxmemory-samples 3 --slave-read-only no
    stateful: true
    volumes:
      - redis-cache-data:/data
    instances: 2
    deploy:
      strategy: ha
      min_health: 0.6
      wait_for_port: 6379
    health_check:
      protocol: tcp
      port: 6379
      interval: 20
      initial_delay: 60
      timeout: 2
    affinity:
      - label==role=app

  sentinel:
    image: ${registry}:redis-sentinel-latest
    build:
      context: ./redis/sentinel
    environment:
      - SERVICE_HOSTNAME=server
      - QUORUM=2
      - DOWN_AFTER=1000
    depends_on:
      - server
    instances: 3
    deploy:
      strategy: ha
      min_health: 0.6
      wait_for_port: 26379

volumes:
  redis-cache-data:
    external: true
  run-magento:
    external: true
```
