### ISSUE TITLE
Master allows multiple vault secrets with the same ENV variable name

### ISSUE THREAD

**Issue by kke** [kontena/kontena#2503]
With a JSON such as:
```json
            secrets: [
              { secret: "foo_MONGODB_URI", name: 'MONGODB_URI', type: 'env' },
              { secret: "foo_VAULT_KEY", name: 'MONGODB_URI', type: 'env' },
              { secret: "foo_VAULT_IV", name: 'MONGODB_URI', type: 'env' }
            ]
```

The master accepts this happily instead of complaining about duplicate secrets.

![image](https://user-images.githubusercontent.com/224971/27334195-28a61610-55d1-11e7-93c0-ed76f93a2891.png)

**Comment by SpComb** [comment]
I think it's an intended feature, which is used to e.g. deploy multiple LE SSL certs to a `kontena/lb`. Some code somewhere in the server or agent will join those envs together into a single env string?

**Comment by SpComb** [comment]
The magic happens in the agent [`Kontena::Models::ServicePod#build_env`](https://github.com/kontena/kontena/blob/master/agent/lib/kontena/models/service_pod.rb#L332):

```ruby
        secrets_hash = {}
        self.secrets.select{|s| s['type'] == 'env'}.each do |s|
          val = secrets_hash[s['name']]
          if val.nil?
            val = s['value']
          else
            val = "#{val}\n#{s['value']}"
          end
          secrets_hash[s['name']] = val
        end
        secrets_hash.each do |name, value|
          env << "#{name}=#{value}"
        end
```

However, I'm not sure if this behavior is actually documented anywhere... it's only show as an example for deploying multiple `kontena/lb` SSL certs from secrets: http://www.kontena.io/docs/using-kontena/loadbalancer.html#an-example-with-2-certificates-wwwdomaincom-and-apidomaincom

```yaml
services:
  loadbalancer:
    image: kontena/lb:latest
    ports:
      - 443:443
    secrets:
      - secret: www_domain_com_cert
        name: SSL_CERTS
        type: env
      - secret: api_domain_com_cert
        name: SSL_CERTS
        type: env
```

This is the main usecase for this that I'm aware of.
