### ISSUE TITLE
Assigning a secret to multiple env's does not work properly.

### ISSUE THREAD

**Issue by Quving** [kontena/kontena#2505]
In the "secrets-area" within the kontena.yml I defined two blocks with the goal to assign a secret to 2 different environment variables:

e.g. 

```
      - secret: ...
      - secret: SECRET_FOO
        name: ENV_FOO
        type: env
      - secret: SECRET_FOO
        name: ENV_BAR
        type: env
      - secret: ...
```

Lead to echo $ENV_FOO --> 2x SECRET_FOO
and $ENV_BAR is not even set. 

I would say, it's a bug.

**Comment by kke** [comment]
Sligthly related to #2503

**Comment by SpComb** [comment]
Confirmed with the following stack YAML:

```yaml
stack: test/secrets-multi
services:
  foo:
    image: redis
    secrets:
      - secret: test-secret
        name: TEST_SECRET
        type: env
      - secret: test-secret
        name: TEST2_SECRET
        type: env
```

The CLI POST's correctly:

```
{ "secrets":[{"secret":"test-secret","name":"TEST_SECRET","type":"env"},{"secret":"test-secret","name":"TEST2_SECRET","type":"env"}] }
```

I suspect this happens because the  lookup for existing grid secrets in [`GridServices::Common#build_grid_service_secrets`](https://github.com/kontena/kontena/blob/v1.3.1/server/app/mutations/grid_services/common.rb#L81), only checks the `secret`, and not the `name`. This happens during service updates.

Confirmed because after a `kontena stack install --no-deploy`, when only running the `GridServices::Create`, the service secrets are actually still correct in `kontena service show`:

```
  secrets: 
    - secret: test-secret
      name: TEST_SECRET
      type: env
    - secret: test-secret
      name: TEST2_SECRET
      type: env
```

Then after a `kontena stack deploy` (which runs `GridServices::Update`), the existing secrets are incorrectly duplicated:

```
  secrets: 
    - secret: test-secret
      name: TEST2_SECRET
      type: env
    - secret: test-secret
      name: TEST2_SECRET
      type: env
```
```
