### ISSUE TITLE
Stack should allow default values to be reset

### ISSUE THREAD

**Issue by daniel-bytes** [kontena/kontena#2576]
In a `kontena.yml` file, if you update the value of a `default` field in a variable, the new value will not be used when executing `kontena stack upgrade`.

It would be nice if there was a `--clear-defaults` command line arguments to `kontena stack upgrade` that would force the default values to be read from the stack file again.

Use case:
```
stack: danb/my-service
version: 0.1.1
variables:
  other_service_url:
    type: string
    default: https://some-service.other-stack.${GRID}.kontena.local
    from:
      env: OTHER_SERVICE_URL
services:
  api:
    environment:
      - OTHER_SERVICE_URL=${other_service_url}
```

Imagine I decide later that `default: https://some-service.other-stack.${GRID}.kontena.local` should actually be `default: http://some-service.other-stack.${GRID}.kontena.local:9876`.  I can't just update the stack file and run a `stack upgrade`.  I need to remove the stack altogether and redeploy, or inject the variable in some other way.
