### ISSUE TITLE
Allow to gain access to host using Agent

### ISSUE THREAD

**Issue by Edke** [kontena/kontena#2602]
It would be great if Kontena Agent would allow to gain shell access to it's host. 

Use case: I have installations where node is in network not reachable from public Internet, gain access to such a host is done with complicated setup's like ssh tunnelling, VPN's, port forwarding etc.

This feature is easy and secure solution, and while Agent serves docker services it also helps to gain access to host, Awesome !!

Currently @jakolehm helped me with workaround solution, some issues with terminal but it works. Proper integration within Agent itself and feature within a box, would be even better.

```bash
$ kontena service create --cmd="-t 1 -m -u -i -n sleep 60000" --privileged --net=host --pid=host nsenter walkerlee/nsenter
$ kontena service deploy nsenter
$ kontena service exec -it nsenter bash
root@small-sun-23 / # id
uid=0(root) gid=0(root) groups=0(root) context=system_u:system_r:kernel_t:s0
```

**Comment by matti** [comment]
`$ kontena stack reg pull matti/nsenter`

```
stack: matti/nsenter
version: 0.0.1
description: kontena node nsenter

services:
  nsenter:
    image: walkerlee/nsenter
    deploy:
      strategy: daemon
    command: "-t 1 -m -u -i -n sleep 2073600"
    privileged: true
    network_mode: host
    pid: host
```
