### ISSUE TITLE
tcp kontena/lb health_check is complicated

### ISSUE THREAD

**Issue by matti** [kontena/kontena#2609]
`kontena/lb` deployed with only tcp services.

the best kontena health_check I came up with is using the stats port:

```
    health_check:
      protocol: tcp
      port: 1000
      interval: 10
      initial_delay: 10
      timeout: 2
```

But I can not use http health check since the stats endpoint requires auth and #1790 is not implemented yet
