### ISSUE TITLE
.kontena.local -> .kontena

### ISSUE THREAD

**Issue by thecatwasnot** [kontena/kontena#264]
I think it's worth considering changing the domain, the .local tld causes conflicts with the avahi daemon on Ubuntu boxes.  I also feel like .local would be more likely to cause conflicts with other vpns, or local network setups in bizarre ways. `service.grid.kontena` feels like a pretty sensible way to address things from my newbie POV.
Originally suggested: https://github.com/kontena/kontena/issues/150#issuecomment-139356536

**Comment by jakolehm** [comment]
Yes, it seems that `.local` is causing a little too much trouble. We need to think this carefully so that we don't blow up existing installations. Maybe this could be some kind of option in the grid settings.

/cc @nevalla @miskun

**Comment by miskun** [comment]
Yes, I like the `service.grid.kontena` namespace. The current `.local` adds no real value in my mind. Just causing some conflicts in existing networks. I also like the idea of having this setting as config parameter for a Grid.

**Comment by colinmollenhour** [comment]
Just wrestled with this for a while.. Only solution that worked was to remove "avahi-daemon" from Ubuntu box. Pretty sure removing .local would make it a non-issue.

**Comment by SpComb** [comment]
Workaround for Ubuntu: the relevant package to remove is `libnss-mdns`; removing that should clear the `hosts: mdns*` entry from `/etc/nsswitch.conf`.

```
$ grep hosts /etc/nsswitch.conf 
hosts:          files mdns4_minimal [NOTFOUND=return] dns
$ sudo apt purge libnss-mdns
...
Removing libnss-mdns:amd64 (0.10-7) ...
libnss-mdns.postrm: Checking NSS setup...
libnss-mdns.postrm: Removing mdns from NSS setup
Purging configuration files for libnss-mdns:amd64 (0.10-7) ...
$ grep hosts /etc/nsswitch.conf 
hosts:          files dns
```

You can then still reinstall it:

```
$ apt install libnss-mdns
...
Setting up libnss-mdns:amd64 (0.10-7) ...
First installation detected...
Checking NSS setup...
$ grep hosts /etc/nsswitch.conf 
hosts:          files mdns4_minimal [NOTFOUND=return] dns
```

**Comment by colinmollenhour** [comment]
What is the purpose of having the grid in the DNS? Nodes can't communicate across grids, can they? If there is no situation in which from one environment you can communicate with multiple grids (VPN?) it seems it would be better to just remove the grid from DNS. For example, I'm configuring monitoring and to aggregate nginx stats with DataDog I would check something like:

```yaml
instances:
  - nginx_status_url: http://nginx-admin-1.web.primary.kontena.local:8081/nginx_status/
    tags:
      - role:admin
  - nginx_status_url: http://nginx-frontend-1.web.primary.kontena.local:8081/nginx_status/
    tags:
      - role:frontend
  - nginx_status_url: http://nginx-frontend-2.web.primary.kontena.local:8081/nginx_status/
    tags:
      - role:frontend
  - nginx_status_url: http://nginx-frontend-3.web.primary.kontena.local:8081/nginx_status/
    tags:
      - role:frontend
```

However, now my config is dependent on the grid name whereas without the grid it would work without having to substitute this in:

```yaml
instances:
  - nginx_status_url: http://nginx-admin-1.web.kontena:8081/nginx_status/
    tags:
      - role:admin
  - nginx_status_url: http://nginx-frontend-1.web.kontena:8081/nginx_status/
    tags:
      - role:frontend
  - nginx_status_url: http://nginx-frontend-2.web.kontena:8081/nginx_status/
    tags:
      - role:frontend
  - nginx_status_url: http://nginx-frontend-3.web.kontena:8081/nginx_status/
    tags:
      - role:frontend
```
