### ISSUE TITLE
volume_from breaks dependancy of services

### ISSUE THREAD

**Issue by Edke** [kontena/kontena#2672]
In stack when combining `volume_from` and `depends_on`/`links`, services that are configured with `volume_from` are deployed before services that are defined in `depends_on`.

Example:
```yaml
---
stack: kraken/test
version: 1.0.2
services:
  web:
    image: web:latest
    volumes_from:
      - data-1
    depends_on:
      - data
      - db
  db:
    image: db:latest
  data:
    image: data:latest
```
Correct deployment order:

1. data or db
2. db or data
3. web

Currently deployed in order:

1. data
2. web
3. db

This behavior breaks dependency as service `web` is deployed before service `db`.
