### ISSUE TITLE
Stack dependencies

### ISSUE THREAD

**Issue by jakolehm** [kontena/kontena#2702]
Stack should have top-level keyword `depends` that describes stack dependencies.

```yaml
stack: user/myapp
depends:
  redis:
    stack: kontena/redis:latest
  postgres:
    stack: kontena/stolon:0.1.0
services:
  api:
    image: user/myapp:1.0
    environment:
      - REDIS_HOST={{ redis }}
      - POSTGRES_HOST={{ postgres }}
```
