### ISSUE TITLE
health_check to have number of consecutive failures / health

### ISSUE THREAD

**Issue by matti** [kontena/kontena#2722]
```
health_check:
  protocol: tcp
  port: 5432
  initial_delay: 180
  interval: 10
  timeout: 1
  **failed_after: 3**
  **healthy_after: 3**
```
