### ISSUE TITLE
Support for custom data-only containers

### ISSUE THREAD

**Issue by ptsurbeleu** [kontena/kontena#2756]
It would be great to have support for custom data-only containers created from an image other than an application defined in your stack. Here is an example of the imaginary relationship between an application and its data-only container defined in a stack YAML:
```
files_container:
  image: xyz/filesonly
  data_only: true

app_container:
  image: xyz/app
  stateful: true
  volumes_from: files_container
```

Here is the link to the original thread at Kontena's forums: [Support for Data Containers](https://forum.kontena.io/t/support-for-data-containers/298/3).

I would be more than happy to help with coding, testing and/or prototyping of the feature.

Thanks!
