### ISSUE TITLE
CLI show-command filtering and formatting

### ISSUE THREAD

**Issue by kke** [kontena/kontena#2763]
Most of the `kontena *** show` commands output something that is almost but not exactly YAML.

For example, `kontena stack show xyz` outputs something like this:

```yaml
twemproxy-redis2:
  created: 2017-09-04T12:55:32.287Z
  state: running
  stack: kke/redis
  expose: - 
  services:
    redis:
      created: 2017-09-04T12:55:32.307Z
...
...
```

If this service was exposing something, the stack show output would actually be valid YAML, but the unescaped `-` in `expose` makes it invalid.

`kontena node show xxx` outputs:

```yaml
foo/core-2:
  id: VPRT:GVF3:YCTO:CYV5:JRGD:432W:SBPS:7UDH:IELG:OUFO:VNHH:PKE5
  agent version: 1.4.0.dev
  docker version: 1.10.3
  connected: yes
  last connect: 2017-09-04T12:16:45.194Z
  os: CoreOS 1122.3.0 (MoreOS)
  drivers:
    storage: overlay
    volume: local
  initial node: no
  labels:
  stats:
    cpus: 1
    filesystem:
      - /var/lib/docker: 0.55 of 15.57 GB
```

This is valid YAML, as long as you use `YAML.load` instead of `safe_load`, which refuses because timestamp is recognized and Time is not by default in the safe classes list.

This all seems quite nice, until you look at the source:

```ruby
# node show
     puts "#{node['id']}:"
      puts "  id: #{node['node_id']}"
      puts "  agent version: #{node['agent_version']}"
      puts "  docker version: #{node['docker_version']}"
...
      puts "  drivers:"
      puts "    storage: #{node['driver']}"
      puts "    volume: #{node['volume_drivers'].to_a.map{|v| v['name']}.join(',')}"
...
      if fs
        puts "    filesystem:"
        fs.each do |filesystem|
          puts "      - #{filesystem['name']}: #{to_gigabytes(filesystem['used'], 2)} of #{to_gigabytes(filesystem['total'], 2)} GB"
        end
      end
```

```ruby
# stack show
      puts "#{stack['name']}:"
      puts "  created: #{stack['created_at']}"
      puts "  updated: #{stack['updated_at']}"
      puts "  services:"
      stack['services'].each do |service|
        show_service(service['id'])
      end

    def show_service(service_id)
      token = require_token
      service = get_service(token, service_id)
      pad = '    '.freeze
      puts "#{pad}#{service['name']}:"
      puts "#{pad}  created: #{service['created_at']}"
      ...
      if service['volumes'].to_a.size > 0
        puts "#{pad}  volumes:"
        service['volumes'].to_a.each do |v|
          puts "#{pad}    - #{v}"
        end
      end
      ...
   end
```

Going through a lot of trouble to create something from a hash that is almost but not quite YAML. 

If it was just a `YAML.dump`ed hash, you could `JSON.dump` it as well.

(interesting side note, YAML 1.2 release announcement says: "The primary objective of this revision is to bring YAML into compliance with JSON as an official subset.". Surprisingly, you can even parse JSON with a YAML parser: `YAML.load(JSON.dump(some_hash)) => no problemo`)

If the commands could output JSON, it could be filtered with the excellent `jq` or with jsonpaths.
