### ISSUE TITLE
Kontena CLI needs a configuration for non-interactive mode

### ISSUE THREAD

**Issue by deiga** [kontena/kontena#2792]
If my `kontena.yml` contains `from: prompt:` variables then I can't run my config on a CI machine.

Please provide a way to pass in answers to prompts or something similar for non-interactive usage

**Comment by kke** [comment]
You can do this by using the `env` resolver, something like:

```yaml
from: 
  env: INSTANCES
  prompt: Number of instances?
```

This way if you have `INSTANCES` env set, the value won't be asked.

#2707 also adds `-v variable_name=value`
