### ISSUE TITLE
Dependent stack variables are not interpolated

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#2799]
From #2707: Trying to interpolate variables like the default `$STACK`/`$GRID` names, any other parent stack variables, or any dependent child stack names does not work in the `depend` stack `variables` section:

```yaml
depends:
  foo:
    stack: deptest-child.yaml
  bar:
    stack: deptest-child.yaml
    variables:
      peers: "foo=redis://$foo:6379/"
```

results in `{"Env": ["PEERS=foo=redis://$foo:6379/"]}` with a literal `$foo`. The dependent stack name variables can only be used by services directly in the parent stack. This prevents child stack services from being able to address or link to services provided by other child stacks.

Same thing for applies for `$STACK`, the service just literally ends up with `foo=redis://$STACK-foo:6379/`.
