### ISSUE TITLE
[1.4] Stack reader does not allow interpolating `to: env: FOO` using `${FOO}`

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#2815]
Regression from https://github.com/kontena/kontena/pull/2707#discussion_r138916318: with a stack variable `foo` using `to: env: FOO`, you can no longer interpolate `${FOO}`:

```
 [error] RuntimeError : Undeclared variable 'FOO' in /kontena/test/test/to-env.yaml:12 --       - FOO=${FOO}
```

This pattern is widely used in existing stacks, so this is a serious regression. There should be an e2e spec for it.

#### `to-env.yaml`
```yaml
stack: test/to-env
variables:
  foo:
    type: string
    from:
      prompt:
    to:
      env: FOO
services:
  redis:
    image: redis
    environment:
      - FOO=${FOO}
```

#### `kontena stack validate test/to-env.yaml `
```
> Enter foo : foo
 [error] RuntimeError : Undeclared variable 'FOO' in /kontena/test/test/to-env.yaml:12 --       - FOO=${FOO}
         See /root/.kontena/kontena.log or run the command again with environment DEBUG=true set to see the full exception
```

#### `kontena stack validate test/to-env.yaml `
```
> Enter foo : foo
---
stack: test/to-env
variables:
  foo:
    label: foo
    type: string
    from:
      prompt: 
      env: foo
    to:
      env: FOO
    errors: {}
    value: foo
  STACK:
    label: STACK
    type: string
    from:
      env: STACK
    to:
      env: STACK
    errors: {}
    value: to-env
  GRID:
    label: GRID
    type: string
    from:
      env: GRID
    to:
      env: GRID
    errors: {}
    value: validate
services:
  redis:
    image: redis
    environment:
    - FOO=foo
```
