### ISSUE TITLE
kontena stack validate does not use -v values for the top-level stack

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#2828]
It looks like the `kontena stack validate` command does not use `values_from_value_options` for the top-level stack itself, only for dependent child stacks.

I would expect `kontena stack validate -v foo=bar` to not prompt for the value of `foo`. The `kontena stack install -v foo=asdf` command works as expected.

#### `kontena stack validate -v foo=bar test/to-env.yaml`

```
> Enter foo : 
```

#### `to-env.yaml`
```yaml
stack: test/to-env
variables:
  foo:
    type: string
    from:
      prompt:
    to:
      env: FOO
services:
  redis:
    image: redis
    environment:
      - FOO=${FOO}
```
