### ISSUE TITLE
Kontena certificate show outputs raw yaml

### ISSUE THREAD

**Issue by jakolehm** [kontena/kontena#2957]
Which is not really inline with other commands. 

Two options:

* fix `certificate show` to match other commands
* fix all other commands to output raw yaml

**Comment by SpComb** [comment]
Looking at the difference between commands like `certificate show` and `service show`, the `certificate show` output should omit the YAML document separator (`---`), and the `id` should be a top-level hash key, with the remaining fields underneath it:

```yaml
---
id: development/test.188.226.131.23.xip.io
subject: test.188.226.131.23.xip.io
valid_until: '2017-12-14T13:34:00.000+00:00'
alt_names:
- test3.188.226.131.23.xip.io
auto_renewable: true
```

vs

```yaml
development/test.188.226.131.23.xip.io
  subject: test.188.226.131.23.xip.io
  valid_until: '2017-12-14T13:34:00.000+00:00'
  alt_names:
  - test3.188.226.131.23.xip.io
  auto_renewable: true
```

In terms of the technical implementation, that shouldn't require replacing the `puts YAML.dump` with hand-written `puts` lines...
