### ISSUE TITLE
Stack file validation errors are undescriptive

### ISSUE THREAD

**Issue by japsu** [kontena/kontena#2969]
Case in point:

```yaml
 [done] Parsing kontena.yml
(/Users/japsu/Work/leonidas-platform/drone/kontena.yml)  YAML validation failed! Aborting.

- kontena.yml:
  - services:
      agent:
        environment: is not valid
```

Here the faulty line was was

```yaml
      DOCKER_API_VERSION: 1.24
```

which is a `number` instead of `string`. Please tell me that in the error message.
