### ISSUE TITLE
Stack YAML interpolator does not properly skip variable interpolate/evaluate heredocs

### ISSUE THREAD

**Issue by kke** [kontena/kontena#2972]
Something like this works as designed:

```yaml
variables:
  foo:
    from:
      interpolate: foo://${xyz}
```

Because the reader has this:

```ruby
      # @param [String] content - content of YAML file
      def interpolate(content, use_opto: true, substitutions: {}, raise_on_unknown: false, warnings: true)
        content.split(/[\r\n]/).map.with_index do |row, line_num|
          # skip lines that opto may be interpolating
          if row.strip.start_with?('interpolate:') || row.strip.start_with?('evaluate:')
            row
          else
```

It however will not work correctly with something like this:

```yaml
variables:
  foo:
    from:
      interpolate: |
        CONFIG_XYZ = xyzxyz
        CONFIG_FOO = ${foo}
```

I'm not sure what the effects are, if any.
