### ISSUE TITLE
Similarly named stack services using volumes_from will get unnecessarily deployed as dependent services

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#2983]
With two copies of a stack using `volumes_from` installed:

```yaml
stack: test/volumes-from
services:
  redis:
    image: redis
  backup:
    image: redis
    volumes_from:
      - redis-%s
    command: pretend-to-backup-redis
```

Deploying any `redis` services in any stack will also trigger deplyos for the `backup` services in all such stacks:

```
I, [2017-10-31T15:41:08.432469 #9]  INFO -- GridServiceDeployer: service development/volumes-from-1/redis has been deployed
I, [2017-10-31T15:41:08.439884 #9]  INFO -- GridServiceSchedulerWorker: deploying dependent service development/volumes-from-2/backup of deployed service development/volumes-from-1/redis
I, [2017-10-31T15:41:08.444446 #9]  INFO -- GridServiceSchedulerWorker: deploying dependent service development/volumes-from-1/backup of deployed service development/volumes-from-1/redis
```

This is because [`GridService#dependant_services`](https://github.com/kontena/kontena/blob/3d608c58a0c0ce046e3a3f2065c39431b2fbc13f/server/app/models/grid_service.rb#L247-L248) is not scoping the queries for the service name by the stack.

The unnecessary deploys should be harmless, so this is a minor issue.
