### ISSUE TITLE
Agent configures LB HTTP health checks for a HTTP LB service with health_check.protocol=tcp

### ISSUE THREAD

**Issue by jnummelin** [kontena/kontena#3020]
If I have a service with http health check and change that to tcp check, agent still goes and configures `.../health_check_uri` on Etcd. This makes LB config to use that endpoint as the health check for the upstreams.

LB config `health_check_uri`  should only be set if the health check protocol is `http`

## Workaround:

```
kontena etcd rm /kontena/haproxy/lb-stack/lb/services/service-a/health_check_uri
```

**Comment by SpComb** [comment]
It's not an "out-of-sync" bug as such, you don't need to change the service from a http -> tcp health check for this to happen. The issue is that the loadbalancer etcd configuration does not care about the `health_check.protocol`, it only cares about the `KONTENA_LB_MODE` env. This issue is about having a service with `health_check.protocol=tcp` and `KONTENA_LB_MODE=http`: the LB will still get configured with a HTTP health check, while the agent will do TCP health checks.

The [`GridServiceHealthCheck.uri`](https://github.com/kontena/kontena/blob/d2a8ef67cffbe62805f0b61419f9a74df84c3ae8/server/app/models/grid_service_health_check.rb#L4) defaults to `/`, and it will always get [serialized](https://github.com/kontena/kontena/blob/d2a8ef67cffbe62805f0b61419f9a74df84c3ae8/server/app/serializers/rpc/service_pod_serializer.rb#L121) as a container `io.kontena.health_check.uri` label, even if the `health_check.protocol` is `tcp`. The agent [`Kontena::LoadBalancers::Configurer`](https://github.com/kontena/kontena/blob/d2a8ef67cffbe62805f0b61419f9a74df84c3ae8/agent/lib/kontena/load_balancers/configurer.rb#L51)  does not look at the `io.kontena.health_check.protocol`, it only looks at the `KONTENA_LB_MODE=http` env and the `io.kontena.health_check.uri` label:


## Example

#### `healthcheck-tcp.yaml`

```yaml
stack: test/healthcheck-tcp
variables:
  lb:
    type: string
    from:
      service_link:
        prompt: LB service
        image: kontena/lb
services:
  whoami:
    image: jwilder/whoami
    links:
      - $lb
    environment:
      - KONTENA_LB_MODE=http
      - KONTENA_LB_INTERNAL_PORT=8000
      - KONTENA_LB_VIRTUAL_PATH=/
    health_check:
      protocol: tcp
      port: 8000
      interval: 10
      timeout: 2
```

#### `DEBUG=api kontena service show healthcheck-tcp/redis`

Notice that the CLI will hide the `health_check` `uri` for non-http protocols, but it's actually there in the API as `"/"`: https://github.com/kontena/kontena/blob/d2a8ef67cffbe62805f0b61419f9a74df84c3ae8/cli/lib/kontena/cli/services/services_helper.rb#L203

```json
   "health_check" : {
      "timeout" : 2,
      "initial_delay" : 10,
      "protocol" : "tcp",
      "uri" : "/",
      "interval" : 10,
      "port" : 8000
   },
```

```
test/healthcheck-tcp/whoami:
  created: 2017-11-07T13:59:23.062Z
  updated: 2017-11-07T13:59:23.062Z
  stack: test/healthcheck-tcp
  desired_state: running
  image: jwilder/whoami:latest
  revision: 1
  stack_revision: 1
  stateful: no
  scaling: 1
  strategy: ha
  read_only: no
  stop_grace_period: 10s
  deploy_opts:
  dns: whoami.healthcheck-tcp.test.kontena.local
  env: 
    - KONTENA_LB_MODE=http
    - KONTENA_LB_INTERNAL_PORT=8000
    - KONTENA_LB_VIRTUAL_PATH=/
  links: 
    - ingress-lb/lb
  health check:
    protocol: tcp
    port: 8000
    timeout: 2
    interval: 10
    initial_delay: 10
  health status:
    healthy: 1
    total: 1
  instances:
    healthcheck-tcp/whoami/1:
      scheduled_to: terom-test
      deploy_rev: 2017-11-07 13:59:24 UTC
      rev: 2017-11-07 13:59:24 UTC
      state: running
      containers:
        healthcheck-tcp.whoami-1 (on terom-test):
          dns: whoami-1.healthcheck-tcp.test.kontena.local
          ip: 10.81.128.20
          public ip: 188.226.181.18
          health: healthy (2s ago)
          status: running
```

#### `kontena container inspect terom-test/healthcheck-tcp.whoami-1 | jq '.Config.Labels, .Config.Env'`
```json
{
  "io.kontena.container.deploy_rev": "2017-11-07 13:59:24 UTC",
  "io.kontena.container.name": "healthcheck-tcp.whoami-1",
  "io.kontena.container.overlay_cidr": "10.81.128.20/16",
  "io.kontena.container.overlay_network": "kontena",
  "io.kontena.container.pod": "healthcheck-tcp.whoami-1",
  "io.kontena.container.service_revision": "1",
  "io.kontena.container.stop_grace_period": "10",
  "io.kontena.container.type": "container",
  "io.kontena.grid.name": "test",
  "io.kontena.health_check.initial_delay": "10",
  "io.kontena.health_check.interval": "10",
  "io.kontena.health_check.port": "8000",
  "io.kontena.health_check.protocol": "tcp",
  "io.kontena.health_check.timeout": "2",
  "io.kontena.health_check.uri": "/",
  "io.kontena.load_balancer.internal_port": "8000",
  "io.kontena.load_balancer.mode": "http",
  "io.kontena.load_balancer.name": "ingress-lb/lb",
  "io.kontena.platform.name": "test",
  "io.kontena.service.id": "5a01bc3b5bb83500075da84f",
  "io.kontena.service.instance_number": "1",
  "io.kontena.service.name": "whoami",
  "io.kontena.stack.name": "healthcheck-tcp"
}
```
```json
[
  "KONTENA_LB_MODE=http",
  "KONTENA_LB_INTERNAL_PORT=8000",
  "KONTENA_LB_VIRTUAL_PATH=/",
  "KONTENA_SERVICE_ID=5a01bc3b5bb83500075da84f",
  "KONTENA_SERVICE_NAME=whoami",
  "KONTENA_GRID_NAME=test",
  "KONTENA_PLATFORM_NAME=test",
  "KONTENA_STACK_NAME=healthcheck-tcp",
  "KONTENA_NODE_NAME=terom-test",
  "KONTENA_SERVICE_INSTANCE_NUMBER=1",
  "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
  "PORT=8000"
]
```

#### `kontena etcd ls -r /kontena/haproxy`
```
 [done] Retrieving keys from etcd     
/kontena/haproxy
/kontena/haproxy/ingress-lb
/kontena/haproxy/ingress-lb/lb
/kontena/haproxy/ingress-lb/lb/services
/kontena/haproxy/ingress-lb/lb/services/healthcheck-tcp-whoami
/kontena/haproxy/ingress-lb/lb/services/healthcheck-tcp-whoami/balance
/kontena/haproxy/ingress-lb/lb/services/healthcheck-tcp-whoami/health_check_uri
/kontena/haproxy/ingress-lb/lb/services/healthcheck-tcp-whoami/virtual_path
/kontena/haproxy/ingress-lb/lb/services/healthcheck-tcp-whoami/upstreams
/kontena/haproxy/ingress-lb/lb/services/healthcheck-tcp-whoami/upstreams/healthcheck-tcp.whoami-1
/kontena/haproxy/ingress-lb/lb/tcp-services
/kontena/haproxy/ingress-lb/lb/certs
/kontena/haproxy/ingress-lb/lb/certs/bundle
```

#### `kontena etcd get /kontena/haproxy/ingress-lb/lb/services/healthcheck-tcp-whoami/health_check_uri`
```
/
```
