### ISSUE TITLE
e2e entrypoints spec uses uncommited run! method

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#3059]
The e2e specs for stack/service entrypoints in #2950 mistakenly use the non-existant `run!` helper - the the specs still passed on my machine, but I never ended up commiting the exception-raising `run!` helper as part of that PR-fix.

```
  19) stack service entrypoint for a stack service with an entrypoint configures the container with the nested /w/w entrypoint
      Failure/Error: run! 'kontena stack install sleep.yml'
      
      NoMethodError:
        undefined method `run!' for #<RSpec::ExampleGroups::StackServiceEntrypoint::ForAStackServiceWithAnEntrypoint:0x0000562c84719420>
        Did you mean?  run
      # ./spec/features/stack/services/entrypoint_spec.rb:7:in `block (4 levels) in <top (required)>'
      # ./spec/support/shell.rb:33:in `block in with_fixture_dir'
      # ./spec/support/shell.rb:32:in `chdir'
      # ./spec/support/shell.rb:32:in `with_fixture_dir'
      # ./spec/features/stack/services/entrypoint_spec.rb:6:in `block (3 levels) in <top (required)>'

  20) stack service entrypoint for a stack service with an entrypoint in network_mode=host configures the container with the correct entrypoint
      Failure/Error: run! 'kontena stack install etcdctl-watch.yml'
      
      NoMethodError:
        undefined method `run!' for #<RSpec::ExampleGroups::StackServiceEntrypoint::ForAStackServiceWithAnEntrypointInNetworkModeHost:0x0000562c83ef8700>
        Did you mean?  run
      # ./spec/features/stack/services/entrypoint_spec.rb:26:in `block (4 levels) in <top (required)>'
      # ./spec/support/shell.rb:33:in `block in with_fixture_dir'
      # ./spec/support/shell.rb:32:in `chdir'
      # ./spec/support/shell.rb:32:in `with_fixture_dir'
      # ./spec/features/stack/services/entrypoint_spec.rb:25:in `block (3 levels) in <top (required)>'
```
