### ISSUE TITLE
Stack depends mutates ${STACK}

### ISSUE THREAD

**Issue by jakolehm** [kontena/kontena#3144]
Example:

```
stack: jakolehm/fn
depends:
  redis:
    stack: kontena/redis-sentinel
  mariadb:
    stack: kontena/mariadb
    variables:
      user: fn
      db: fn
      mem_limit: 512
variables:
  mariadb_pwd:
    type: string
    from:
      vault: ${STACK}-mariadb-password
  mq_url:
    type: string
    from:
      vault: ${STACK}-mq-url
      interpolate: mysql://fn:${mariadb_pwd}@tcp(db.${mariadb}.${GRID}.kontena.local:3306)/fn
    to:
      vault: ${STACK}-mq-url
```

`${STACK}` should be `fn` in variables section but it actually has mutated to `fn-mariadb`.

**Comment by kke** [comment]
But then again, not mutating could cause unwanted overlaps.  

The dependent stack name is in a variable, so this would work:

```yaml
depends:
  mariadb:
    stack: kontena/mariadb
variables:
  mariadb_pwd:
    type: string
    from:
      vault: ${mariadb}-mariadb-password
```

Mutating `${STACK}` would cause problems in the dependent stack with something like

```yaml
  db_uri: db.${STACK}.${GRID}.kontena.local
```

because `$STACK` would point to something else than the current stack name.

**Comment by kke** [comment]
The mariadb stack has this.

```yaml
      vault: ${STACK}-password
```

Then take another stack, `kontena/mongo-rs`, it has this:

```yaml
      vault: ${STACK}-password
```

If `$STACK` was statically set to the parent stack name, you would end up with mongo and mariadb sharing the same vault key for password, even if either was deep down in some deeply nested dependency chain. 

At least `kontena/kafka-cluster`, `kontena/zookeeper` and `kontena/kong` would get broken by the `$STACK.$GRID` problem:

```yaml
      # {%   capture broker %}kafka-{{ i }}.{{ STACK }}.{{ GRID }}.kontena.local:9092{% endcapture %}
```

```yaml
      - KONG_PG_HOST=postgres.${STACK}.${GRID}.kontena.local
```

```yaml
      # {%   capture server %}server.{{ i }}=zookeeper-{{ i }}.{{ STACK }}.{{ GRID }}.kontena.local:2888:3888 {% endcapture %}
```

It's not possible to install the child stacks with the same stack name, so you would then need something like `$CURRENT_STACK_NAME` to build links like the ones above, but that is what `$STACK` already is. 

@SpComb thoughts?

**Comment by kke** [comment]
Nevermind, the problem is that $STACK is changed for the parent stack when returning from the child installations, that indeed is a bug.

**Comment by SpComb** [comment]
Yeah. The [`kontena stack install`](https://github.com/kontena/kontena/blob/master/cli/lib/kontena/cli/stacks/install_command.rb) sets the `ENV['stack']`, then recurses into the dependencies, and then evaluates the variables using `ENV['stack']`. That means that it ends up using the `ENV['stack']` set by the last child dependency.

Looks like the [`kontena stack upgrade`](https://github.com/kontena/kontena/blob/fea8711fffae58d7d0d27576888335e4df7ec7ff/cli/lib/kontena/cli/stacks/upgrade_command.rb#L87) command is implemented differently, and I think it might actually end up using the correct value of `$STACK` here: it flattens the dependent stacks, and thens explicitly sets the envs before each stack is evaluated.

**Comment by SpComb** [comment]
Yes, this is broken for `kontena stack install`, but it actually works for `kontena stack upgrade`:

```yaml
stack: test/deptest
depends:
  foo:
    stack: deptest-child.yaml
  bar:
    stack: deptest-child.yaml
    variables:
      peers: "foo=redis://foo:6379/"
variables:
  test:
    type: string
    value: "STACK=${STACK}"
services:
  redis:
    image: redis
    environment:
      - STACK=$STACK
      - test=$test
```

```
$ bin/kontena stack install test/deptest.yaml 
...
$ bin/kontena container inspect core-01/deptest.redis-1 | jq '.Config.Env'
[
  "STACK=deptest-bar",
  "test=STACK=deptest-bar",
  ...
```

```
$ bin/kontena stack upgrade deptest test/deptest.yaml 
...
$ bin/kontena container inspect core-01/deptest.redis-1 | jq '.Config.Env'
[
  "STACK=deptest",
  "test=STACK=deptest",
  ...
```
