### ISSUE TITLE
support service-level `extends` from kontena stack registry 

### ISSUE THREAD

**Issue by jonasrmichel** [kontena/kontena#3255]
Currently, the `extends` keyword only supports service-level extension from local stack files. It would be fantastic if stacks in the kontena stack registry could also be extended.

In fact, the kontena docs seem to indicate this is already possible.
```
redis:
  extends:
    stack: kontena/redis:0.1.0
    service: redis
```
Modified from https://kontena.io/docs/using-kontena/stack-file.html#using-extends-to-extend-docker-compose-file-with-kontena

But the above snippet gives an error.
```
[error] Errno::ENOENT : No such file or directory @ rb_sysopen - /<file path elided>/kontena/redis:0.1.0
```
