### ISSUE TITLE
CLI stack build does not report YAML validation errors

### ISSUE THREAD

**Issue by SpComb** [kontena/kontena#3266]
The `kontena stack build` command does not report YAML validation errors. Instead, it fails with a `Not found any service with a build option` (sic) error because the resulting `services` is an empty `Hash` (WTF: shouldn't it be an array?)

```
$ bundle exec bin/kontena stack build -f test/validation.yaml 
Not found any service with a build option
$ bundle exec bin/kontena stack validate test/validation.yaml 
(/home/kontena/kontena/kontena/cli/test/validation.yaml)  YAML validation failed! Aborting.

- validation.yaml:
  - services:
      test:
        health_check:
          port: integer required
```

```yaml
stack: test/validation
services:
  test:
    build: .
    image: test/validation
    health_check:
      protocol: http
```
