### ISSUE TITLE
Daemon not restored after drain

### ISSUE THREAD

**Issue by colinmollenhour** [kontena/kontena#3279]
I used 'drain' to do some maintenance on a service that is deployed with 'daemon' strategy and the containers were cleaned up as expected, but after I was done and returning the node to 'active' Kontena doesn't seem to think one service needs to be re-scheduled to the nodes that were drained.

```
$ kontena node update --availability drain db2
$ kontena node update --availability drain db3
...
$ kontena node update --availability active db2
$ kontena node update --availability active db3
```

#### Expected:

The service should be terminated on db2 and db3 and then restored.

#### Actual:

The service was terminated but was not restored. Even `kontena service deploy` did not restore it.

```
 $ kontena service deploy galera/node
 [done] Deploying service galera/node
⊛ Deployed instance primary/galera/node-1 to node db1
```

There are other services that were in-fact deployed so I'm thinking the difference may be the existence of the "mysql-data" volume which is specified in the stack file. I do not want to lose this volume's contents when draining, I want to restore the services using the existing volume data.
```
...
  node:
    image: "${registry}:mariadb-galera-latest"
    build:
      context: ./mariadb-galera
      args:
        CONFIG_ENV: ${mysql_config_env}
    environment:
      - GCOMM_MINIMUM=3
      - LISTEN_WHEN_HEALTHY=8082
    secrets:
      - secret: GALERA_XTRABACKUP_PASSWORD
        name: XTRABACKUP_PASSWORD
        type: env
    command: "node seed,node"
    stateful: true
    volumes:
      - mysql-data:/var/lib/mysql
    deploy:
      strategy: daemon
      min_health: 0.6
      wait_for_port: 8082
    instances: 1
    affinity:
      - label==role=db
      - label==role=db-node

volumes:
  mysql-data:
    external: true
```

Kontena master logs after "deploy" command:

```
I, [2018-02-15T06:13:05.983621 #19]  INFO -- GridServiceSchedulerWorker: starting primary/galera/node deploy
I, [2018-02-15T06:13:05.999467 #19]  INFO -- GridServiceDeployer: starting to deploy primary/galera/node
I, [2018-02-15T06:13:06.078192 #19]  INFO -- GridServiceDeployer: throttling service instance primary/galera/node deploy because of min_health limit (1 instances in-progress)
I, [2018-02-15T06:13:06.089362 #19]  INFO -- GridServiceInstanceDeployer: Deploying service instance primary/galera/node-1 to node db1 at 2018-02-15 06:13:06 UTC...
I, [2018-02-15T06:13:07.163919 #19]  INFO -- GridServiceInstanceDeployer: waited 1.0s of 300.0s until: service primary/galera/node-1 is running on node primary/db1 at 2018-02-15 06:13:06 UTC yielded GridServiceInstance
I, [2018-02-15T06:13:07.273412 #19]  INFO -- GridServiceDeployer: service primary/galera/node has been deployed
```

**Comment by jnummelin** [comment]
Based on the master logs, it seems that it really doesn't even consider the service to need more than single instance. Hence it does not deploy it on the re-activated nodes. Double check that after your maintenance, there's all the needed labels in place for the nodes.

As you have flagged the service `stateful: true`, the containers on the nodes should be only **stopped** during `drain`. So you should see those containers in `docker ps -a` list, as well as in `kontena service show galera/node` in stopped state. Do you actually see those containers still existing?

How does the `kontena volume show mysql-data` look like?

**Comment by colinmollenhour** [comment]
> Double check that after your maintenance, there's all the needed labels in place for the nodes.

The labels are and were always intact. 

Unfortunately I needed to get this working again so I took the sledgehammer approach and completely removed the stack and re-installed it which did get the services deploying again on the other nodes... I will update if the issue is produced again.

Here is the current output of the volume command, db3 volume was never deleted manually but db2 was:

```
mysql-data:
  id: primary/mysql-data
  created: 2017-04-07T20:58:47.195Z
  scope: grid
  driver: local
  driver_opts:
  instances:
    - name: mysql-data
      node: db1
    - name: mysql-data
      node: db2
    - name: mysql-data
      node: db3
  services:
    - primary/galera/seed
    - primary/galera/node
```
