### ISSUE TITLE
Volume added to stack file does not get added to service on stack upgrade

### ISSUE THREAD

**Issue by colinmollenhour** [kontena/kontena#3375]
I wanted to add a new volume to a service already running but it seems that a stack upgrade does not add new volumes to existing services. Without support for `--volumes` in the `kontena service update` command (#3274) there seems to be no way to add the volume without destroying the stack. :(

**Comment by bucha** [comment]
Hi Colin,

I just made a quick test, but was unable to reproduce the problem.

First draft:
```
stack: cartware/test
services:
  nginx:
    image: nginx:latest
```

I installed the stack via `kontena stack install`.
Then I changed the stack and added a volume.

Second draft:
```
stack: cartware/test
services:
  nginx:
    image: nginx:latest
    volumes:
      - /root/html:/usr/share/nginx/html
```

I upgraded the stack via `kontena stack upgrade test`:
```
[done] Reading stack test from master
 [done] Parsing kontena.yml
 [done] Processing stack test
 [done] Analyzing upgrade

> Calculated changes:
  ~ test
    ~ test/nginx

 [done] Upgrading stack test
 [done] Triggering deployment of stack test
 [done] Waiting for deployment to start
 [done] Deploying service nginx
```

Thereafter I ssh'ed into the node and added some dummy text into `/root/html/index.html`.
While the first draft installation showed the nginx welcome page, the second draft showed my dummy text.

Did you follow the same scheme?

Cheers,
Alex

**Comment by colinmollenhour** [comment]
The only difference I see in what you and I did was my before already had a volume and so my after had two volumes. Also I am running 1.4.3.

**Comment by bucha** [comment]
Negative.
I added a second volume such this:
```
stack: cartware/test
services:
  nginx:
    image: nginx:latest
    volumes:
      - /root/html:/usr/share/nginx/html
      - /root/anotherfolder:/usr/share/nginx/html/test
```

And added some content to `/root/anotherfolder/index.html`

Opening `/test` via the browser or curl reveals my new content.

Did you try updating kontena?
`kontena-cli 1.5.2` here.
