### ISSUE TITLE
LB's all the way down - fails

### ISSUE THREAD

**Issue by hans-d** [kontena/kontena#391]
Testing some chained LB's, eg using the following `kontena.yml`
```
lb-main:
  image: kontena/lb:latest
  ports:
    - "8091:80"

lb-sub-2:
  image: kontena/lb:latest
  ports:
    - "8092:80"
  environment:
    - KONTENA_LB_VIRTUAL_PATH=/test
  links:
    - lb-main

lb-sub-3:
  image: kontena/lb:latest
  ports:
    - "8093:80"
  environment:
    - KONTENA_LB_VIRTUAL_PATH=/test
  links:
    - lb-sub-2

test-nginx:
  extends:
    file: docker-compose.yml
    service: test-nginx
  ports:
    - "8094:80"
  environment:
    - KONTENA_LB_VIRTUAL_PATH=/test
  links:
    - lb-sub-3
```
Ports are there to manually verify the various containers.

lb-sub-3 and test-nginx work fine, the others fail.

Not sure where it fails exactly (eg no haproxy logging available yet, see #318), but noticing this config in lb-sub-2: (other configs seem correct)

```
listen http-in
    bind *:80
    reqadd X-Forwarded-Proto:\ https if { ssl_fc }
    reqadd X-Forwarded-Port:\ 443 if { ssl_fc }

        acl host_infra-lb-sub-3_path url_beg /test
        use_backend infra-lb-sub-3 if host_infra-lb-sub-3_path

        acl host_infra-test-nginx_path url_beg /test
        use_backend infra-test-nginx if host_infra-test-nginx_path

backend infra-lb-sub-3
    option                  forwardfor
    balance                 roundrobin
    reqrep ^([^\ :]*)\ /test[/]?(.*)     \1\ /\2
    server infra-lb-sub-3-1 10.81.20.254:80 check

backend infra-test-nginx
    option                  forwardfor
    balance                 roundrobin
    reqrep ^([^\ :]*)\ /test[/]?(.*)     \1\ /\2
```
note the missing server part with infra-test-nginx. Most likely it fails here
