### ISSUE TITLE
alternate dockerfile not recognised?

### ISSUE THREAD

**Issue by hans-d** [kontena/kontena#396]
docker-compose-build.yml
```
test:
  build: .
  dockerfile: Dockerfile-test
```
kontena.yml
```
test:
  extends:
    file: docker-compose-build.yml
    service: test
  image: registry.kontena.local/test:latest
```

```
$ kontena app build test
'.' does not have Dockerfile
```
