### ISSUE TITLE
using kontena-haproxy 

### ISSUE THREAD

**Issue by dferrantelli** [kontena/kontena#488]
Especially with that branch that has letsencrypt, i'd love to use the haproxy container as a service for load balancing a few webapps that need to be SSL. Having that container handle LE certs on it's own would be wonderful. I am having trouble getting it to work correctly though (I am new-ish to docker, and very new to kontena), and can't seem to find documentation on how to use/configure the haproxy service. I wasn't sure this was the right place for this, but it's searcheable, and i hope this will help others.

**Comment by jakolehm** [comment]
Yes, we have an experimental branch of kontena haproxy image that has built-in LE (acme) client. You could try to setup it like this (just an example):

```
haproxy:
  image: kontena/haproxy:acme
  ports:
    - 80:80
    - 443:443
  environment:
    - LE_EMAIL=your@email.com
    - LE_DOMAINS=www.domain.com,api.domain.com
    - BACKENDS=%{project}-lb:80

lb:
  image: kontena/lb:latest

web:
  image: nginx:latest
  environment:
    - KONTENA_LB_VIRTUAL_HOSTS=www.domain.com
  links:
    - lb

api:
  image: my/api:latest
  environment:
    - KONTENA_LB_VIRTUAL_HOSTS=api.domain.com
  links:
    - lb
```

Here haproxy is doing just the ssl termination part and passing traffic to kontena load balancer. Then actual web services (web & api) are linked to load balancer.
