### ISSUE TITLE
How to use kontena load balancing?

### ISSUE THREAD

**Issue by m3adow** [kontena/kontena#630]
Hey,

I recently stumbled upon kontena while searching for a more streamlined version of my self-built consul + registrator + consul-template + haproxy setup for my micro service testlab. I'm currently trying to understand the basics of kontena load balancing, but I struggle.  
Here's the `kontena.yml` I use:
```yml
internet_lb:  
  image: kontena/lb:latest
  ports:
    - 80:80
  deploy:
    strategy: daemon

web1:  
  image: nginx:latest
  environment:
    - KONTENA_LB_INTERNAL_PORT=80
    - KONTENA_LB_MODE=http
    - KONTENA_LB_VIRTUAL_HOSTS=web1.foo.bar
  links:
    - internet_lb
  affinity:
    - node==node_a

web2:
  image: httpd:latest
  environment:
    - KONTENA_LB_INTERNAL_PORT=80
    - KONTENA_LB_MODE=http
    - KONTENA_LB_VIRTUAL_HOSTS=web2.foo.bar
  links:
    - internet_lb
  affinity:
    - node==node_b
```

I'm trying to achieve a state where I can access both web instances from both nodes, but I can't figure it out. The `internet_lb` never properly starts and is just restarted over and over again.

Where is my error?

Best regards
m3adow
