### ISSUE TITLE
Proposal: HTTP health check for services as a platform feature

### ISSUE THREAD

**Issue by christofferh** [kontena/kontena#658]
Could be used by loadbalancer to detect unhealthy instances and remove from rotation. 

First implementation could be simple and just present the info for the instance e.g. `kontena service status my-service.

```
server:
  image: christofferh/www:latest
  environment:
    - KONTENA_LB_INTERNAL_PORT=8080
  links:
    - loadbalancer
  health_check:
    url: /monitor
    timeout: 2 # Timeout seconds
    unhealthy_threshold: 5 # The number of consecutive failed health checks
```

Inspiration:

http://docs.deis.io/en/latest/using_deis/config-application/#custom-health-checks
http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/elb-healthchecks.html
