### ISSUE TITLE
Expose multiple ports via loadbalancer

### ISSUE THREAD

**Issue by tanelih** [kontena/kontena#664]
Is it possible to expose multiple ports of an application via the loadbalancer?

For example, I have a service with the following ports exposed: `8080`, `8081`, `8082`... However I can only set one port with the `KONTENA_LB_INTERNAL_PORT` environment variable. The service is _very_ stateful. :new_moon_with_face:

Is there a way to map exposed ports from the service to the loadbalancer in a `n:n` fashion, e.g. connecting to `8081` in the `lb`, we'd be forwarded to `8081` in the service, `8082` to `8082` in the service and so on...

Thanks :smiley:

**Comment by jakolehm** [comment]
Currently it's not possible. We are going to refactor loadbalancer pretty soon to different codebase and that might bring us possibility to add support for multiple ports.

**Comment by tanelih** [comment]
Are there any known workarounds for this issue? Is it possible to use a different `lb` in front of the application?

**Comment by jakolehm** [comment]
This might work (just an example):

```
lb:
  image: kontena/lb:latest
  ports:
    - "80:80"
    - "443:443"

app-admin-proxy:
  image: kontena/haproxy:latest
  environment:
    - VIRTUAL_HOSTS=%{project}-app=admin.domain.com
    - BACKENDS=%{project}-app:8080
    - KONTENA_LB_VIRTUAL_HOSTS=admin.domain.com
    - KONTENA_LB_INTERNAL_PORT=80
  links:
    - lb

app-www-proxy:
  image: kontena/haproxy:latest
  environment:
    - VIRTUAL_HOSTS=%{project}-app=www.domain.com
    - BACKENDS=%{project}-app:80
    - KONTENA_LB_VIRTUAL_HOSTS=www.domain.com
    - KONTENA_LB_INTERNAL_PORT=80
  links:
    - lb

app:
  image: my/legacy:latest
  stateful: true
```
