### ISSUE TITLE
log_opts disappear after service update

### ISSUE THREAD

**Issue by mtrofimm** [kontena/kontena#768]
$ kontena service show service_1
[...]
```
  log_driver: gelf
  log_opts:
    gelf-address: udp://log_forwarder-logstash_internal:12201
    labels: label1
    env: prod
```
$ kontena service update --image some_new_image service_1

$ kontena service show service_1
```
 log_driver: gelf
  log_opts:
[...]
  status: stopped
  reason: initlogger: Failed to initialize logging driver: gelf: cannot connect to GELF endpoint:  dial udp: missing address
```

$ kontena service update --log-opt "gelf-address=udp://log_forwarder-logstash_internal:12201" --log-opt labels=label1 --log-opt env=prod service_1

$ kontena service show service_1
```
  log_driver: gelf
  log_opts:
    gelf-address: udp://log_forwarder-logstash_internal:12201
    labels: label1
    env: prod
[...]
      status: running

```

server & cli version: 0.14.0
