### ISSUE TITLE
Support docker build arguments on kontena app build command

### ISSUE THREAD

**Issue by nevalla** [kontena/kontena#780]
Docker Compose version 2 enables to use [build arguments](https://docs.docker.com/engine/reference/builder/#arg) on build options:

```
build:
  args:
    buildno: 1
    user: someuser

build:
  args:
    - buildno=1
    - user=someuser
```
