### ISSUE TITLE
Prevent service update with a flag

### ISSUE THREAD

**Issue by jnummelin** [kontena/kontena#882]
It would be nice to have a flag of some kind to state that some services should not be updated even if there would be newer image available.

Consider the following example:
```
version: '2'
name: my-app
services:
  redis:
    image: redis:3.0
    stateful: true
  web:
    image: my-app:latest
```

When ever user deploys the app we will also deploy a new instance of the Redis IF there is a newer image available.

So something like this would be nice:
```
version: '2'
name: my-app
services:
  redis:
    image: redis:3.0
    stateful: true
    update: never|forced-only|always
  web:
    image: my-app:latest
```
