### ISSUE TITLE
Invalid version number yields confusing error message

### ISSUE THREAD

**Issue by timolehto** [kontena/kontena#986]
If you have in your kontena.yml version defined as an integer as appose to string the error message kontena gives is:
```
kontena app build
Kontena error: no implicit conversion of Hash into String
Rerun the command with environment DEBUG=true set to get the full exception
```

Compared to docker-compose which in similar situation gives much more clearer error message:
```
docker-compose build
ERROR: Version in "./docker-compose.yml" is invalid - it should be a string.
```

**Comment by nevalla** [comment]
Kontena should accept numeric value for version. There might be something else wrong in kontena.yml that is not handled correctly. Could you run `DEBUG=true kontena app build`?

**Comment by timolehto** [comment]
Ahaa, I see what you mean. It sometimes accepts numbers, but it depends. So this works:
```
version: 2
name: foo

services:
  bar:
    image: foobar
    build: .
```
This however fails with the above mentioned error:
```
version: 2
name: foo

services:
  bar:
    image: foobar
    build: .
      context: .
      dockerfile: Dockerfile
```
Where as this works just fine:
```
version: '2'
name: foo

services:
  bar:
    image: foobar
    build: .
      context: .
      dockerfile: Dockerfile
```

Debug trace:
```
DEBUG=true kontena app build -f kontti.yml
/Users/timo/.rvm/gems/ruby-2.3.1@laboratory/gems/kontena-cli-0.15.1/lib/kontena/cli/apps/docker_helper.rb:68:in `expand_path': no implicit conversion of Hash into String (TypeError)
	from /Users/timo/.rvm/gems/ruby-2.3.1@laboratory/gems/kontena-cli-0.15.1/lib/kontena/cli/apps/docker_helper.rb:68:in `dockerfile_exist?'
	from /Users/timo/.rvm/gems/ruby-2.3.1@laboratory/gems/kontena-cli-0.15.1/lib/kontena/cli/apps/docker_helper.rb:12:in `block in process_docker_images'
	from /Users/timo/.rvm/gems/ruby-2.3.1@laboratory/gems/kontena-cli-0.15.1/lib/kontena/cli/apps/docker_helper.rb:8:in `each'
	from /Users/timo/.rvm/gems/ruby-2.3.1@laboratory/gems/kontena-cli-0.15.1/lib/kontena/cli/apps/docker_helper.rb:8:in `process_docker_images'
	from /Users/timo/.rvm/gems/ruby-2.3.1@laboratory/gems/kontena-cli-0.15.1/lib/kontena/cli/apps/build_command.rb:23:in `execute'
	from /Users/timo/.rvm/gems/ruby-2.3.1@laboratory/gems/clamp-1.0.0/lib/clamp/command.rb:68:in `run'
	from /Users/timo/.rvm/gems/ruby-2.3.1@laboratory/gems/clamp-1.0.0/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /Users/timo/.rvm/gems/ruby-2.3.1@laboratory/gems/clamp-1.0.0/lib/clamp/command.rb:68:in `run'
	from /Users/timo/.rvm/gems/ruby-2.3.1@laboratory/gems/clamp-1.0.0/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /Users/timo/.rvm/gems/ruby-2.3.1@laboratory/gems/clamp-1.0.0/lib/clamp/command.rb:68:in `run'
	from /Users/timo/.rvm/gems/ruby-2.3.1@laboratory/gems/clamp-1.0.0/lib/clamp/command.rb:133:in `run'
	from /Users/timo/.rvm/gems/ruby-2.3.1@laboratory/gems/kontena-cli-0.15.1/bin/kontena:16:in `<top (required)>'
	from /Users/timo/.rvm/gems/ruby-2.3.1@laboratory/bin/kontena:23:in `load'
	from /Users/timo/.rvm/gems/ruby-2.3.1@laboratory/bin/kontena:23:in `<main>'
	from /Users/timo/.rvm/gems/ruby-2.3.1@laboratory/bin/ruby_executable_hooks:15:in `eval'
	from /Users/timo/.rvm/gems/ruby-2.3.1@laboratory/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by nevalla** [comment]
Actually your YAML example contains a minor error, but still Kontena should handle this better. Right format is:

```
version: '2'
name: foo

services:
  bar:
    image: foobar
    build:
      context: .
      dockerfile: Dockerfile
```

There was extra `.` on build option and YAML format is invalid.

But thanks for reporting this issue, I'll improve YAML parsing to handle and report this kind of situations better.
