### ISSUE TITLE
Where do I point my DNS?

### ISSUE THREAD

**Issue by ianwalter** [kontena/kontena#992]
I set up a loadbalancer and linked it to my Minio app:
```yml
  load_balancer:
    image: kontena/lb:latest
    ports:
      - 443:443
      - 80:80
    secrets:
      - secret: SSL_CERT_LE_TEST_BUNDLE
        name: SSL_CERTS
        type: env
  minio:
    stateful: true
    image: minio/minio
    command: /export
    ports:
      - 9000:9000
    secrets:
      - secret: MINIO_ACCESS_KEY
        name: MINIO_ACCESS_KEY
        type: env
      - secret: MINIO_SECRET_KEY
        name: MINIO_SECRET_KEY
        type: env
    environment:
      - KONTENA_LB_MODE=http
      - KONTENA_LB_BALANCE=roundrobin
      - KONTENA_LB_INTERNAL_PORT=9000
      - KONTENA_LB_VIRTUAL_HOSTS=minio.domain.com
    links:
      - load_balancer
```

I tried pointing an A record for minio.domain.com to the master node and then tried pointing it to the node the loadbalancer container was on, but neither seemed to work. I am able to access the Minio server through the IP address.

**Comment by matti** [comment]
You can not set ports when using loadbalancer (fails "silently")

**Comment by jakolehm** [comment]
@ianwalter it should work by pointing dns to node (or nodes) where loadbalancer is running.

@matti I would say that "you should not expose ports directly" when using loadbalancer. But it's completely possible to set ports while using loadbalancer _if_ those ports are available.

Btw our community slack might be better place for these kind of questions: https://slack.kontena.io/

**Comment by ianwalter** [comment]
@jakolehm Ok, I opened this issue because I think the docs could be more clear. Should I not set ports on the loadbalancer? Because the example in the docs shows setting `80:80`. Also, should I set the deploy strategy to daemon on the loadbalancer or is that how it is configured by default? How does failover work? Are you suggesting setting multiple A records to each node?

**Comment by ianwalter** [comment]
Also, this is what my logs say for the loadbalancer:
```
2016-09-09T02:40:32.000Z kontena-load_balancer-1: Sep  9 02:40:32 localhost haproxy[44]: Server kontena-minio/kontena-minio-1 is DOWN, reason: Layer4 connection problem, info: "Connection refused", check duration: 0ms. 0 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
2016-09-09T02:40:32.000Z kontena-load_balancer-1: Sep  9 02:40:32 localhost haproxy[44]: backend kontena-minio has no server available!
```
But I can access the minio server fine with the IP address and port 9000. So why does the loadbalancer think it's down? Do I have to set `KONTENA_LB_HEALTH_URI`? Because the docs make it seem like thats optional.

**Comment by matti** [comment]
@jakolehm we had an issue with @timolehto that if we set ports to the service when using loadbalancer, the ports would work, but the loadbalancer would not.

It looks very similar here what @ianwalter is seeing. Could you unset ports for the service @ianwalter and try loadbalancer again?

I'm currently AFK so can not verify.

**Comment by nevalla** [comment]
I got load balancing working with and without published ports with these options:

```
version: '2'
services:
  server:
    stateful: true
    image: minio/minio
    command: /export    
    secrets:
      - secret: MINIO_ACCESS_KEY
        name: MINIO_ACCESS_KEY
        type: env
      - secret: MINIO_SECRET_KEY
        name: MINIO_SECRET_KEY
        type: env
    links:
      - loadbalancer
    environment:
      - KONTENA_LB_INTERNAL_PORT=9000
      - KONTENA_LB_VIRTUAL_HOSTS=minio.domain.com
  loadbalancer:
    image: kontena/lb:latest
    deploy:
      strategy: daemon
    ports:
      - 80:80
      - 443:443
```

So nothing special there. I got also 503 in the morning but cannot reproduce it now, which is strange.
